import { createFileRoute } from "@tanstack/react-router";
import { useEffect,useMemo,useState } from "react";
import { Loader2,CheckCircle2,Star } from "lucide-react";
import logo from "@/assets/goatbar-logo.png";

export const Route=createFileRoute("/degustacao/$token")({component:TastingPublicPage});
type Drink={id:string;drink_name:string;drink_description?:string;drink_image?:string};
type Person={slot:number;name:string};
function TastingPublicPage(){
 const {token}=Route.useParams(); const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[done,setDone]=useState(false),[error,setError]=useState("");const [data,setData]=useState<any>(null);
 const [people,setPeople]=useState<Person[]>([1,2,3,4].map(slot=>({slot,name:""})));const [ratings,setRatings]=useState<Record<string,{score:string;comment:string}>>({});const [observations,setObservations]=useState("");const [selections,setSelections]=useState<Record<string,{bride_drink:boolean;groom_drink:boolean}>>({});
 const endpoint=`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/tasting-public`,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
 useEffect(()=>{fetch(endpoint,{method:"POST",headers:{apikey:key,"Content-Type":"application/json"},body:JSON.stringify({action:"get",token})}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);setObservations(j.tasting?.guest_observations||"");setSelections(Object.fromEntries((j.drinks||[]).map((d:any)=>[d.id,{bride_drink:!!d.bride_drink,groom_drink:!!d.groom_drink}])));setPeople([1,2,3,4].map(slot=>({slot,name:j.participants?.find((p:any)=>p.slot===slot)?.name||""})));const next:any={};for(const rr of j.ratings||[]){const p=j.participants.find((x:any)=>x.id===rr.participant_id);if(p)next[`${rr.tasting_drink_id}:${p.slot}`]={score:String(rr.score),comment:rr.comment||""}}setRatings(next)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[token]);
 const canSubmit=useMemo(()=>Object.values(ratings).some(x=>Number(x.score)>=1),[ratings]);
 const submit=async()=>{setSaving(true);setError("");try{const rows=Object.entries(ratings).filter(([,v])=>Number(v.score)>=1&&Number(v.score)<=10).map(([k,v])=>{const [tasting_drink_id,slot]=k.split(":");return{tasting_drink_id,slot:Number(slot),score:Number(v.score),comment:v.comment}});const r=await fetch(endpoint,{method:"POST",headers:{apikey:key,"Content-Type":"application/json"},body:JSON.stringify({action:"submit",token,participants:people,ratings:rows,observations,selections:Object.entries(selections).map(([tasting_drink_id,v])=>({tasting_drink_id,...v}))})});const j=await r.json();if(!r.ok)throw new Error(j.error);setDone(true)}catch(e:any){setError(e.message)}finally{setSaving(false)}};
 if(loading)return <main className="min-h-screen grid place-items-center bg-background"><Loader2 className="h-8 w-8 animate-spin text-primary"/></main>;
 if(error&&!data)return <main className="min-h-screen grid place-items-center bg-background p-6"><div className="max-w-md text-center"><img src={logo} className="h-14 mx-auto mb-6"/><h1 className="text-xl font-bold">Degustação indisponível</h1><p className="mt-2 text-muted-foreground">{error}</p></div></main>;
 if(done)return <main className="min-h-screen grid place-items-center bg-background p-6"><div className="max-w-md text-center"><CheckCircle2 className="h-14 w-14 text-primary mx-auto"/><h1 className="text-2xl font-bold mt-4">Avaliações salvas!</h1><p className="text-muted-foreground mt-2">Obrigado por participar da degustação da GOAT Bar.</p></div></main>;
 return <main className="min-h-screen bg-background text-foreground"><header className="border-b bg-black text-white"><div className="max-w-5xl mx-auto px-5 py-7 flex items-center justify-between"><img src={logo} alt="GOAT Bar" className="h-14 w-auto"/><div className="text-right"><span className="block text-[10px] uppercase tracking-[0.32em] opacity-70">Experiência GOAT Bar</span><span className="font-display text-lg tracking-wide">Degustação</span></div></div></header><div className="max-w-5xl mx-auto p-4 sm:p-6 space-y-6"><div><h1 className="font-display text-3xl font-bold">{data?.tasting?.events?.event_name||data?.tasting?.events?.client_name||"Degustação GOAT Bar"}</h1><p className="text-muted-foreground mt-1">Dê uma nota de 1 a 10 para cada drink. Campos sem nota não entram na média.</p></div>
 <section className="rounded-2xl border bg-surface p-4"><h2 className="font-bold mb-3">Participantes</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{people.map((p,i)=><input key={p.slot} value={p.name} onChange={e=>setPeople(x=>x.map((v,j)=>j===i?{...v,name:e.target.value}:v))} placeholder={`Pessoa ${p.slot}`} className="h-11 rounded-xl border bg-background px-3 text-sm"/>)}</div></section>
 {(data?.drinks||[]).map((d:Drink)=><section key={d.id} className="rounded-2xl border bg-surface overflow-hidden"><div className="grid md:grid-cols-[220px_1fr]"><div className="bg-muted min-h-48">{d.drink_image?<img src={d.drink_image} alt={d.drink_name} className="w-full h-full object-cover"/>:<div className="h-full grid place-items-center text-muted-foreground"><Star/></div>}</div><div className="p-5"><h2 className="text-xl font-bold">{d.drink_name}</h2>{d.drink_description&&<p className="text-sm text-muted-foreground mt-1">{d.drink_description}</p>}<div className="mt-4 flex flex-wrap gap-2"><label className={`rounded-full border px-3 py-2 text-xs font-bold cursor-pointer ${selections[d.id]?.bride_drink?"border-primary bg-primary/10 text-primary":""}`}><input className="mr-2" type="checkbox" checked={!!selections[d.id]?.bride_drink} onChange={e=>setSelections(x=>({...x,[d.id]:{...(x[d.id]||{bride_drink:false,groom_drink:false}),bride_drink:e.target.checked}}))}/>Drink da noiva</label><label className={`rounded-full border px-3 py-2 text-xs font-bold cursor-pointer ${selections[d.id]?.groom_drink?"border-primary bg-primary/10 text-primary":""}`}><input className="mr-2" type="checkbox" checked={!!selections[d.id]?.groom_drink} onChange={e=>setSelections(x=>({...x,[d.id]:{...(x[d.id]||{bride_drink:false,groom_drink:false}),groom_drink:e.target.checked}}))}/>Drink do noivo</label></div><div className="grid sm:grid-cols-2 gap-3 mt-5">{people.map(p=>{const k=`${d.id}:${p.slot}`,v=ratings[k]||{score:"",comment:""};return <div key={p.slot} className="rounded-xl border p-3"><div className="text-xs font-bold mb-2">{p.name||`Pessoa ${p.slot}`}</div><div className="flex gap-2"><input type="number" min="1" max="10" step="0.5" value={v.score} onChange={e=>setRatings(x=>({...x,[k]:{...v,score:e.target.value}}))} placeholder="Nota 1–10" className="w-28 h-10 rounded-lg border bg-background px-3"/><input value={v.comment} onChange={e=>setRatings(x=>({...x,[k]:{...v,comment:e.target.value}}))} placeholder="Comentário (opcional)" className="flex-1 min-w-0 h-10 rounded-lg border bg-background px-3 text-sm"/></div></div>})}</div></div></div></section>)}
 <section className="rounded-2xl border bg-surface p-5"><h2 className="font-bold text-lg">Observações da degustação</h2><p className="text-sm text-muted-foreground mt-1">Registre detalhes especiais, como monograma, anel do drink da noiva, decoração, acabamento ou outras preferências.</p><textarea value={observations} onChange={e=>setObservations(e.target.value)} rows={5} placeholder="Ex.: incluir monograma no drink da noiva; usar anel no acabamento; ajustar decoração..." className="mt-4 w-full rounded-xl border bg-background p-3 text-sm"/></section>{error&&<p className="text-sm text-destructive">{error}</p>}<button disabled={saving||!canSubmit} onClick={submit} className="w-full h-12 rounded-xl bg-primary text-primary-foreground font-bold disabled:opacity-50">{saving?"Salvando...":"Enviar avaliações"}</button><p className="text-center text-xs text-muted-foreground pb-6">GOAT Bar · Avaliação da degustação</p></div></main>
}