import { useEffect,useMemo,useState } from "react";
import { Calendar,Download,ExternalLink,GlassWater,Loader2,MapPin,Pencil,Play,Plus,Save,Trophy } from "lucide-react";
import { toast } from "sonner";
import type { Drink } from "@/lib/mock-data";
import { TASTING_LOCATION,tastingService,type Tasting,type TastingBundle } from "@/services/tasting-service";

const statusLabel:Record<string,string>={planning:"Planejamento",scheduled:"Agendada",completed:"Concluída",finalized:"Finalizada",cancelled:"Cancelada"};
const toLocalInput=(value:string|null)=>{if(!value)return"";const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const formatDate=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"long"}).format(new Date(value));
const formatTime=(value:string)=>new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit"}).format(new Date(value));

export function DegustacaoTab({eventId,eventName,drinks}:{eventId:string;eventName:string;drinks:Drink[]}){
 const [items,setItems]=useState<Tasting[]>([]),[selected,setSelected]=useState<TastingBundle|null>(null),[busy,setBusy]=useState(false),[chosen,setChosen]=useState<string[]>([]),[editing,setEditing]=useState(false);
 const [scheduledAt,setScheduledAt]=useState("");
 const load=async(id?:string)=>{const list=await tastingService.list(eventId);setItems(list);const target=id||selected?.tasting.id||list[0]?.id;if(target){const b=await tastingService.get(target);setSelected(b);setChosen(b.drinks.map(d=>d.drink_id));setScheduledAt(toLocalInput(b.tasting.scheduled_at));setEditing(!b.tasting.scheduled_at||b.tasting.status==="planning")}else setSelected(null)};
 useEffect(()=>{load().catch(e=>toast.error(e.message))},[eventId]);
 const rank=useMemo(()=>selected?tastingService.ranking(selected):[],[selected]);
 const create=async()=>{setBusy(true);try{const t=await tastingService.create(eventId);await load(t.id);setEditing(true)}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
 const save=async()=>{if(!selected)return;if(!scheduledAt){toast.error("Defina a data e o horário da degustação.");return}if(!chosen.length){toast.error("Selecione pelo menos um drink para a degustação.");return}setBusy(true);try{await tastingService.setDrinks(selected.tasting.id,drinks.filter(d=>chosen.includes(d.id)));await tastingService.update(selected.tasting.id,{scheduled_at:new Date(scheduledAt).toISOString(),location:TASTING_LOCATION,status:"scheduled",public_enabled:true} as Partial<Tasting>);await tastingService.syncCalendar(selected.tasting.id);await load(selected.tasting.id);setEditing(false);toast.success("Degustação agendada e sincronizada com o Google Agenda.")}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
 const start=()=>{if(!selected?.tasting.scheduled_at)return;window.open(`${window.location.origin}/degustacao/${selected.tasting.public_token}`,"_blank","noopener,noreferrer")};
 if(!selected)return <div className="rounded-2xl border border-dashed p-10 text-center"><Trophy className="h-10 w-10 mx-auto text-primary mb-3"/><h3 className="font-bold text-lg">Nenhuma degustação criada</h3><p className="text-sm text-muted-foreground mt-1">Crie a degustação, escolha os drinks e agende a data.</p><button onClick={create} disabled={busy} className="mt-5 rounded-xl bg-primary text-primary-foreground px-5 py-2.5 font-bold inline-flex items-center gap-2"><Plus className="h-4 w-4"/>Criar degustação</button></div>;
 const finished=selected.tasting.status==="completed"||selected.tasting.status==="finalized";
 return <div className="space-y-5">
  <div className="flex flex-wrap items-center gap-2">{items.map(t=><button key={t.id} onClick={()=>load(t.id)} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${selected.tasting.id===t.id?"bg-primary text-primary-foreground":"bg-surface"}`}>{t.scheduled_at?new Date(t.scheduled_at).toLocaleDateString("pt-BR"):"A definir"} · {statusLabel[t.status]||t.status}</button>)}<button onClick={create} disabled={busy} className="rounded-full border px-3 py-1.5 text-xs font-bold"><Plus className="inline h-3 w-3"/> Nova</button></div>

  {editing&&!finished?<section className="rounded-2xl border bg-surface p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-bold text-lg flex items-center gap-2"><Calendar className="h-5 w-5 text-primary"/>Agendar degustação</h3><p className="text-sm text-muted-foreground mt-1">O local é fixo: {TASTING_LOCATION}. Selecione a data, o horário e os drinks que serão preparados.</p></div></div><div className="mt-5 max-w-sm"><label className="text-xs font-bold">Data e horário</label><input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} className="mt-1 w-full h-11 rounded-xl border bg-background px-3"/></div><div className="mt-5"><div className="flex items-center justify-between gap-3"><div><h4 className="font-bold">Drinks da degustação</h4><p className="text-xs text-muted-foreground">Nesta etapa exibimos somente os nomes, sem fotos.</p></div><span className="text-xs font-bold text-muted-foreground">{chosen.length} selecionado(s)</span></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-3">{drinks.map(d=><label key={d.id} className={`rounded-xl border px-3 py-2.5 flex items-center gap-2 cursor-pointer ${chosen.includes(d.id)?"border-primary bg-primary/5":""}`}><input type="checkbox" checked={chosen.includes(d.id)} onChange={e=>setChosen(x=>e.target.checked?[...x,d.id]:x.filter(id=>id!==d.id))}/><span className="text-sm font-semibold">{d.nome}</span></label>)}</div></div><div className="flex flex-wrap gap-2 mt-5"><button onClick={save} disabled={busy} className="rounded-xl bg-primary text-primary-foreground px-4 py-2.5 font-bold inline-flex items-center gap-2">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Agendar degustação</button>{selected.tasting.scheduled_at&&<button onClick={()=>setEditing(false)} className="rounded-xl border px-4 py-2.5 font-bold">Cancelar edição</button>}</div></section>:
  <section className="rounded-2xl border bg-surface p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs uppercase tracking-[0.2em] text-muted-foreground font-bold">Degustação agendada</div><h3 className="font-display text-2xl font-bold mt-1">{eventName}</h3></div><span className="rounded-full border px-3 py-1 text-xs font-bold">{statusLabel[selected.tasting.status]||selected.tasting.status}</span></div>{selected.tasting.scheduled_at&&<div className="grid sm:grid-cols-3 gap-3 mt-5"><div className="rounded-xl border bg-background p-4"><Calendar className="h-4 w-4 text-primary mb-2"/><div className="text-xs text-muted-foreground">Data</div><div className="font-bold capitalize">{formatDate(selected.tasting.scheduled_at)}</div></div><div className="rounded-xl border bg-background p-4"><Calendar className="h-4 w-4 text-primary mb-2"/><div className="text-xs text-muted-foreground">Horário</div><div className="font-bold">{formatTime(selected.tasting.scheduled_at)}</div></div><div className="rounded-xl border bg-background p-4"><MapPin className="h-4 w-4 text-primary mb-2"/><div className="text-xs text-muted-foreground">Local</div><div className="font-bold">{TASTING_LOCATION}</div></div></div>}<div className="mt-5"><div className="flex items-center gap-2 font-bold"><GlassWater className="h-4 w-4 text-primary"/>Drinks que serão preparados</div><div className="flex flex-wrap gap-2 mt-3">{selected.drinks.map(d=><span key={d.id} className="rounded-full border bg-background px-3 py-1.5 text-sm font-semibold">{d.drink_name}</span>)}</div></div><div className="flex flex-wrap gap-2 mt-5">{!finished&&<button onClick={start} className="rounded-xl bg-primary text-primary-foreground px-5 py-2.5 font-bold inline-flex items-center gap-2"><Play className="h-4 w-4"/>Iniciar degustação</button>}{!finished&&<button onClick={()=>setEditing(true)} className="rounded-xl border px-4 py-2.5 font-bold inline-flex items-center gap-2"><Pencil className="h-4 w-4"/>Editar agendamento</button>}{selected.tasting.google_calendar_html_link&&<a href={selected.tasting.google_calendar_html_link} target="_blank" rel="noreferrer" className="rounded-xl border px-4 py-2.5 font-bold inline-flex items-center gap-2"><ExternalLink className="h-4 w-4"/>Google Agenda</a>}</div></section>}

  {finished&&<section className="rounded-2xl border bg-surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold text-lg flex items-center gap-2"><Trophy className="h-5 w-5 text-primary"/>Resumo da degustação</h3><p className="text-sm text-muted-foreground">Ranking pela média das notas registradas por todos os participantes.</p></div><button onClick={()=>tastingService.downloadPdf(selected,eventName)} className="rounded-xl border px-4 py-2 font-bold inline-flex items-center gap-2"><Download className="h-4 w-4"/>Gerar PDF</button></div><div className="mt-4 divide-y">{rank.map((d,i)=><div key={d.id} className="py-4 flex items-center gap-3"><div className="text-xl font-black w-10">{i+1}º</div><div className="flex-1"><b>{d.drink_name}</b><p className="text-xs text-muted-foreground">{d.count} avaliação(ões)</p></div><div className="text-xl font-black text-primary">{d.count?d.average.toFixed(1):"—"}</div></div>)}</div></section>}
 </div>
}
