import { useEffect,useMemo,useState } from "react";
import { Calendar,Copy,Download,ExternalLink,Loader2,Plus,Save,Trophy } from "lucide-react";
import { toast } from "sonner";
import type { Drink } from "@/lib/mock-data";
import { tastingService,type Tasting,type TastingBundle } from "@/services/tasting-service";

export function DegustacaoTab({eventId,eventName,drinks}:{eventId:string;eventName:string;drinks:Drink[]}){
 const [items,setItems]=useState<Tasting[]>([]),[selected,setSelected]=useState<TastingBundle|null>(null),[busy,setBusy]=useState(false),[chosen,setChosen]=useState<string[]>([]);
 const load=async(id?:string)=>{const list=await tastingService.list(eventId);setItems(list);const target=id||selected?.tasting.id||list[0]?.id;if(target){const b=await tastingService.get(target);setSelected(b);setChosen(b.drinks.map(d=>d.drink_id))}else setSelected(null)};
 useEffect(()=>{load().catch(e=>toast.error(e.message))},[eventId]);
 const rank=useMemo(()=>selected?tastingService.ranking(selected):[],[selected]);
 const create=async()=>{setBusy(true);try{const t=await tastingService.create(eventId);await load(t.id)}finally{setBusy(false)}};
 const save=async()=>{if(!selected)return;setBusy(true);try{await tastingService.setDrinks(selected.tasting.id,drinks.filter(d=>chosen.includes(d.id)));const date=(document.getElementById("tasting-date") as HTMLInputElement)?.value;const location=(document.getElementById("tasting-location") as HTMLInputElement)?.value;await tastingService.update(selected.tasting.id,{scheduled_at:date?new Date(date).toISOString():null,location:location||null,status:date?"scheduled":"planning"} as any);if(date)await tastingService.syncCalendar(selected.tasting.id);await load(selected.tasting.id);toast.success("Degustação salva.")}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
 const copy=()=>{if(!selected)return;navigator.clipboard.writeText(`${window.location.origin}/degustacao/${selected.tasting.public_token}`);toast.success("Link da degustação copiado.")};
 if(!selected)return <div className="rounded-2xl border border-dashed p-10 text-center"><Trophy className="h-10 w-10 mx-auto text-primary mb-3"/><h3 className="font-bold text-lg">Nenhuma degustação criada</h3><p className="text-sm text-muted-foreground mt-1">Crie a degustação, escolha os drinks e depois agende a data.</p><button onClick={create} disabled={busy} className="mt-5 rounded-xl bg-primary text-primary-foreground px-5 py-2.5 font-bold inline-flex gap-2"><Plus className="h-4 w-4"/>Criar degustação</button></div>;
 return <div className="space-y-5">
  <div className="flex flex-wrap gap-2">{items.map(t=><button key={t.id} onClick={()=>load(t.id)} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${selected.tasting.id===t.id?"bg-primary text-primary-foreground":"bg-surface"}`}>{t.scheduled_at?new Date(t.scheduled_at).toLocaleDateString("pt-BR"):"A definir"} · {t.status}</button>)}<button onClick={create} className="rounded-full border px-3 py-1.5 text-xs font-bold"><Plus className="inline h-3 w-3"/> Nova</button></div>
  <div className="grid lg:grid-cols-3 gap-5"><section className="lg:col-span-2 rounded-2xl border bg-surface p-5"><h3 className="font-bold text-lg flex items-center gap-2"><Calendar className="h-5 w-5 text-primary"/>Agendamento</h3><div className="grid sm:grid-cols-2 gap-3 mt-4"><div><label className="text-xs font-bold">Data e horário</label><input id="tasting-date" type="datetime-local" defaultValue={selected.tasting.scheduled_at?new Date(new Date(selected.tasting.scheduled_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):""} className="mt-1 w-full h-11 rounded-xl border bg-background px-3"/></div><div><label className="text-xs font-bold">Local</label><input id="tasting-location" defaultValue={selected.tasting.location||""} placeholder="Local da degustação" className="mt-1 w-full h-11 rounded-xl border bg-background px-3"/></div></div><div className="flex flex-wrap gap-2 mt-4"><button onClick={save} disabled={busy} className="rounded-xl bg-primary text-primary-foreground px-4 py-2 font-bold inline-flex gap-2">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Salvar e sincronizar agenda</button><button onClick={copy} className="rounded-xl border px-4 py-2 font-bold inline-flex gap-2"><Copy className="h-4 w-4"/>Copiar formulário</button>{selected.tasting.google_calendar_html_link&&<a href={selected.tasting.google_calendar_html_link} target="_blank" rel="noreferrer" className="rounded-xl border px-4 py-2 font-bold inline-flex gap-2"><ExternalLink className="h-4 w-4"/>Google Agenda</a>}</div></section>
  <section className="rounded-2xl border bg-surface p-5"><h3 className="font-bold">Status</h3><div className="mt-3 text-sm space-y-2"><p><b>{selected.drinks.length}</b> drinks</p><p><b>{selected.participants.filter(p=>p.name).length}</b> participantes</p><p>Agenda: <b>{selected.tasting.google_calendar_sync_status}</b></p><p>Formulário: <b>{selected.tasting.public_enabled?"ativo":"fechado"}</b></p></div></section></div>
  <section className="rounded-2xl border bg-surface p-5"><h3 className="font-bold text-lg">Drinks da degustação</h3><p className="text-sm text-muted-foreground">Selecione no catálogo atual. Nome, descrição e foto ficam registrados na degustação.</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-4">{drinks.map(d=><label key={d.id} className={`rounded-xl border p-3 flex gap-3 cursor-pointer ${chosen.includes(d.id)?"border-primary bg-primary/5":""}`}><input type="checkbox" checked={chosen.includes(d.id)} onChange={e=>setChosen(x=>e.target.checked?[...x,d.id]:x.filter(id=>id!==d.id))}/>{d.imagem&&<img src={d.imagem} className="h-14 w-14 rounded-lg object-cover"/>}<div><b className="text-sm">{d.nome}</b><p className="text-xs text-muted-foreground line-clamp-2">{d.descricao}</p></div></label>)}</div></section>
  {selected.ratings.length>0&&<section className="rounded-2xl border bg-surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold text-lg flex gap-2"><Trophy className="h-5 w-5 text-primary"/>Resultado e ranking</h3><p className="text-sm text-muted-foreground">A média considera somente notas preenchidas.</p></div><button onClick={()=>tastingService.downloadPdf(selected,eventName)} className="rounded-xl border px-4 py-2 font-bold inline-flex gap-2"><Download className="h-4 w-4"/>Gerar PDF</button></div><div className="mt-4 divide-y">{rank.map((d,i)=><div key={d.id} className="py-3 flex items-center gap-3"><div className="text-xl font-black w-10">{i+1}º</div><div className="flex-1"><b>{d.drink_name}</b><p className="text-xs text-muted-foreground">{d.count} avaliação(ões)</p></div><div className="text-xl font-black text-primary">{d.count?d.average.toFixed(1):"—"}</div><label className="text-xs flex items-center gap-1"><input type="checkbox" checked={d.selected_for_event} onChange={async e=>{await tastingService.toggleSelected(d.id,e.target.checked);await load(selected.tasting.id)}}/> servir no evento</label></div>)}</div><button onClick={async()=>{await tastingService.applySelectedToEvent(eventId,selected);toast.success("Drinks selecionados aplicados ao evento.")}} className="mt-4 rounded-xl bg-primary text-primary-foreground px-4 py-2 font-bold">Aplicar selecionados ao evento</button></section>}
 </div>
}