import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, apikey, content-type, x-request-id",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const MENU_LOGO_DATA_URL = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABBoAAAV2CAYAAAA0nd/KAAAACXBIWXMAAAsS
AAALEgHS3X78AAAgAElEQVR4nOzdwW1bWZbH4TOGFwS4sBiBlEEpg3IGVgZW
RdDuCEaTgSqCliMYVQZ0BCNlIEdAaUGAu5oFybJKJckk9Scv3+P3AULbFE0e
oDfdP5x733/9+eefRf/NppOTqjp58vJRVZ3ufBgAAAD6avy+9QS8zWw6WcaC
k8XP43hwWlUfmgwGAADAQRIaOmKxkXD66Oeoqn5tORMAAAA8JTTsoUdR4ePi
PwUFAAAAOkFo2AOz6WQZFZY/jjsAAADQSUJDA4uNhY9VdVbCAgAAAD0iNOzI
YmvhvOZh4ZemwwAAAMCWCA1b9CgunFXVcdtpAAAAYPuEhjBxAQAAgEMmNATM
ppOjmseFLyUuAAAAcMCEhjeYTSdnNQ8MnxqPAgAAAHtBaFiT7QUAAAB4mdCw
osUjKS9qfveCx1ECAADAM4SGn1hc7vilqj63ngUAAAD2ndDwgtl08rHmGwy/
tp0EAAAAukNoeEJgAAAAgM0JDQuP7mBwRAIAAAA2dPChYfEUicsSGAAAAODN
3rUeoKXZdHJRVXclMgAAAEDEQW40LO5huKqq47aTAAAAQL8cVGhY3MNwWVWf
Go8CAAAAvXQwRydm08mXqropkQEAAAC2pvcbDbPp5LTmWwweVwkAAABb1uuN
hsVlj/9XIgMAAADsRC83GhZ3MVyVwAAAAAA71buNhtl0cl7zuxhEBgAAANix
3mw0zKaTo5rfxfC59SwAAABwqHoRGhYXPl5X1XHrWQAAAOCQdf7oxOKoxLhE
BgAAAGiu0xsNs+nkqhyVAAAAgL3RydCwuI9hXFW/NB4FAAAAeKRzRycW9zHc
lMgAAAAAe6dToWE2nZyV+xgAAABgb3UmNCwuffzfqvrQeBQAAADgBZ0IDbPp
5KKq/tN6DgAAAOB1e38ZpCdLAAAAQHfs9UaDyAAAAADdsrehQWQAAACA7tnL
0CAyAAAAQDftXWgQGQAAAKC79io0iAwAAADQbXsTGkQGAAAA6L69CA0iAwAA
APRD89Awm04uS2QAAACAXmgaGmbTyXlV/avlDAAAAEBOs9Awm07Oquo/rb4f
AAAAyGsSGmbTyWlVXbX4bgAAAGB7dh4aZtPJUVWNq+rDrr8bAAAA2K4WGw3j
EhkAAACgl3YaGhaPsfxll98JAAAA7M7OQsPiCRMeYwkAAAA9tpPQsLj80RMm
AAAAoOe2HhoWlz9eb/t7AAAAgPZ2sdFwVVXHO/geAAAAoLGthobZdPKlqj5t
8zsAAACA/bG10DCbTk6q6mJbnw8AAADsn21uNFxX1Yctfj4AAACwZ7YSGmbT
yUVV/bKNzwYAAAD2Vzw0LB5l+d/pzwUAAAD23zY2Gq628JkAAABAB0RDw+Ip
E45MAAAAwIGKhQZPmQAAAACSGw2X5SkTAAAAcNAioWE2nXysqk+JzwIAAAC6
K7XRcBX6HAAAAKDD3hwaFhdAHgdmAQAAADruTaFhNp0clQsgAQAAgIW3bjRc
lAsgAQAAgIWNQ8PicZb/yo0CAAAAdN1bNhouUkMAAAAA/bBRaFhsM3zOjgIA
AAB03aYbDRfJIQAAAIB+WDs02GYAAAAAXrLJRsNFeggAAACgH9YKDbYZAAAA
gNesu9HwZStTAAAAAL2wcmiYTSdHVXW+vVEAAACArltno+G8qj5saQ4AAACg
B9YJDY5NAAAAAK9aKTTMppOzqjre8iwAAABAx6260XC+zSEAAACAfvhpaFg8
0vLT9kcBAAAAum6VjYazrU8BAAAA9MIqocElkAAAAMBKXg0Ns+nktFwCCQAA
AKzoZxsNthkAAACAlf0sNLifAQAAAFjZi6FhNp2cVdWHHc4CAAAAdNxrGw22
GQAAAIC1CA0AAABAzLOhYTadfCzHJgAAAIA1vbTRYJsBAAAAWJvQAAAAAMT8
IzTMppOTqjre/SgAAABA1z230fBx10MAAAAA/fBcaHBsAgAAANiIjQYAAAAg
5m+hYTadnJbHWgIAAAAberrR8LHFEAAAAEA/CA0AAABAzNPQcNpkCgAAAKAX
/goNs+nkpKqO240CAAAAdN3jjQbbDAAAAMCbCA0AAABAzOPQ8LHVEAAAAEA/
2GgAAAAAYt5VVc2mk6Oq+tB4FgAAAKDjlhsNthkAAACANxMaAAAAgJhlaDhp
OQQAAADQDzYaAAAAgBgbDQAAAEDMMjQcN50CAAAA6IV3P38LAAAAwGqEBgAA
ACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAA
AABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYA
AAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgA
AAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQG
AAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZo
AAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKE
BgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBG
aAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABi
hAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAg
RmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAA
YoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAA
IEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAA
AGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAA
ACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAA
AABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYA
AAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgA
AAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQG
AAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZo
AAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYt63HgA4KP+uqpvWQwAA
fzmvqs+thwD6RWgAduW3wXB01XoIAOBvxrPppEpsAIIcnQB2QWQAgD01GI7O
q+pr6zmA/hAagG0TGQBgz4kNQJLQAGzTv0UGAOiGRWy4bT0H0H1CA7BNLn4E
gG65bz0A0H1CAwAAABAjNAAAAAAxQgMAAAAQIzQAAAAAMUIDAAAAECM0AAAA
ADFCAwAAABAjNAAAAAAxQgMAAAAQIzQAAAAAMUIDAAAAECM0AAAAADFCAwAA
ABAjNAAAAAAxQgMAAAAQIzQAAAAAMUIDAAAAECM0AAAAADFCAwAAABAjNAAA
AAAxQgMAAAAQIzQAAAAAMUIDAAAAECM0AAAAADFCAwAAABAjNAAAAAAxQgMA
AAAQIzQAAAAAMUIDAAAAECM0AAAAADFCAwAAABAjNAAAAAAxQgMAAAAQIzQA
AAAAMUIDAAAAECM0AAAAADFCAwAAABAjNAAAAAAxQgMAAAAQIzQAAAAAMUID
AAAAECM0AAAAADFCAwAAABAjNAAAAAAxQgMAAAAQIzQAAAAAMUIDAAAAECM0
AAAAADFCAwAAABAjNAAAAAAx72bTyUnrIQAAAIB+eFdVJ62HAAAAAPrB0QkA
AAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgA
AAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQG
AAAAIOVGaAAAAABS7oUGAAAAIGIwHI2FBgAAACDhe5U7GgAAAICMmyqhAQAA
AMgQGgAAAICYcZXQAAAAAGTYaAAAAAAivg+Go/sqoQEAAAB4u5vlH4QGAAAA
4K3Gyz8IDQAAAMBb2WgAAAAAMgbD0Xj5Z6EBAAAAeItvj/8iNAAAAABvcfP4
L0IDAAAA8Bbjx38RGgAAAIC3sNEAAAAARHwfDEd3j18QGgAAAIBNjZ++IDQA
AAAAmxo/fUFoAAAAADY1fvqC0AAAAABs4h/3M1QJDQAAAMBmxs+9KDQAAAAA
mxg/96LQAAAAAGxi/NyLQgMAAACwrmfvZ6gSGgAAAID1jV/6hdAAAAAArGv8
0i+EBgAAAGBd45d+ITQAAAAA63jxfoYqoQEAAABYz/VrvxQaAAAAgHWMX/ul
0AAAAACsY/zaL4UGAAAAYFXfBsPR/WtvEBoAAACAVb16P0OV0AAAAACsTmgA
AAAAIm5fe6zlktAAAAAArOJqlTcJDQAAAMAqfnpsokpoAAAAAH7u2yrHJqqE
BgAAAODnrlZ9o9AAAAAAvOahVjw2USU0AAAAAK+7HgxH96u+WWgAAAAAXnO5
zpuFBgAAAOAlt4Ph6GadfyA0AAAAAC9Za5uhSmgAAAAAnrfWJZBLQgMAAADw
nMt1LoFcEhoAAACA51xt8o+EBgAAAOCpr4Ph6G6Tfyg0AAAAAE9dbPoPhQYA
AADgsY23GaqEBgAAAODvLt7yj4UGAAAAYOlN2wxVQgMAAADww8VbP0BoAAAA
AKqqfn/rNkOV0AAAAABUPVRgm6FKaAAAAACqLgbD0X3ig4QGAAAAOGzfB8PR
ZerDhAYAAAA4bOfJDxMaAAAA4HD9MRiOxskPFBoAAADgMD1UeJuhSmgAAACA
QxW7APIxoQEAAAAOz7fkBZCPCQ0AAABwWLZyZGJJaAAAAIDDcj4Yju629eFC
AwAAAByOr4Ph6HqbXyA0AAAAwGG4raov2/4SoQEAAAD676HmRybiT5l4SmgA
AACA/vsyGI5udvFFQgMAAAD029fBcHS1qy8TGgAAAKC/vg2Go/NdfqHQAAAA
AP10W1Vnu/5SoQEAAAD6Z2eXPz4lNAAAAEC/PFTVx11d/viU0AAAAAD9ct4q
MlQJDQAAANAnvw2Go+uWAwgNAAAA0A+/7fIxli8RGgAAAKD79iIyVAkNAAAA
0HV7ExmqhAYAAADosr2KDFVV71sPAAAAAKztoarOBsPRuPUgTwkNAAAA0C0P
VfWx5SMsX+PoBAAAAHTHbVWd7mtkqBIaAAAAoCv+qPkmw13rQV7j6AQAAADs
v98Hw9GX1kOsQmgAAACA/fVQVeeD4ei69SCrcnQCAAAA9tNtzY9KdCYyVAkN
AAAAsI9+rz1+ssRrHJ0AAACA/dG5oxJP2WgAAACA/fBHVZ10OTJU2WgAAACA
1jq/xfCYjQYAAABo52v1YIvhMRsNAAAAsHvfa77FMG49SJrQAAAAALvzUFWX
g+HoovUg2yI0AAAAwG58raovg+HovvUg2yQ0AAAAwHb9UfPAcNd6kF0QGgAA
AGA7vlXVRR/vYXiN0AAAAABZBxkYloQGAAAAyPhaVVeHGhiWhAYAAADY3ENV
Xdd8g+Gu8Sx7QWgAAACA9X2vqsuabzD0+ikS6xIaAAAAYHV/1DwuXLceZF8J
DQAAAPC65fbCteMRPyc0AAAAwD89VNVVzbcXbhrP0ilCAwAAAMwtL3a8djRi
c0IDAAAAh+x7/YgL48az9ILQAAAAwKH5VvO4MHYsIk9oAAAAoO+WWwvjmscF
j6PcIqEBAACAvrmtqpv6ERbumk5zYIQGAAAAuu5bzaPCTdlYaE5oAAAAoEu+
1Two3FTVjTsW9o/QAAAAwD66raq7+ntUuGs5EKsRGgAAAGjle/2ICfc1P/5w
b0uh24QGAAAAtuW25gHhbvFzX4uoICb0l9AAAAAkLP8PZcJJVR2HPou8x/9d
3y1+qn5sJdRgOBrveij2h9AAAAAsXVXVZf0zGNzs+y3+s+nkqKpOV3jrqu87
Xbx3FadV9WHF97bwUPMI8Jy7+hEKXnrN9gFrERoAAICqqhoMR1etZ9jUIoSM
V3z79RZHebPZdPLxyUt3LkGkS4QGAACAPeLYAV33rvUAAAAAQH8IDQAAAECM
0AAAAADECA0AAABAjNAAAAAAxAgNAAAAQIzQAAAAAMQIDQAAAECM0AAAAADE
CA0AAABAjNAAAAAAxAgNAAAAQIzQAAAAAMQIDQAAAECM0AAAAADECA0AAABA
jNAAAAAAxAgNAAAAQIzQAAAAAMQIDQAAAECM0AAAAADECA0AAABAjNAAAAAA
xAgNAAAAQIzQAAAAAMQIDQAAAECM0AAAAADECA0AAABAjNAAAAAAxAgNAAAA
QIzQAAAAAMQIDQAAAECM0AAAAADECA0AAABAjNAAAAAAxAgNAAAAQIzQAAAA
AMQIDQAAAECM0AAAAADECA0AAABAjNAAAAAAxAgNAAAAQIzQAAAAAMQIDQAA
AECM0AAAAADECA0AAABAjNAAAAAAxAgNAAAAQIzQAAAAAMQIDQAAAECM0AAA
AADECA0AAABAjNAAAAAAxAgNAAAAQIzQAAAAAMQIDQAAAECM0AAAAADECA0A
AABAjNAAAAAAxAgNAAAAQIzQAAAAAMQIDQAAAECM0AAAAADECA0AAABAjNAA
AAAAxAgNAAAAQIzQAAAAAMQIDQAAAECM0AAAAADECA0AAABAjNAAAAAAxAgN
AAAAQIzQAAAAAMQIDQAAAECM0AAAAADECA0AAABAjNAAAAAAxAgNAAAAQIzQ
AAAAAMQIDQAAAECM0AAAAADECA0AAABAjNAAAAAAxAgNAAAAQIzQAAAAAMQI
DQAAAECM0AAAAADECA0AAABAjNAAAAAAxAgNAAAAQIzQAAAAAMQIDQAAAECM
0AAAAADECA0AAABAjNAAAAAAxAgNAAAAQMz71gMAAPTFbDo5raqj1nMAQEN3
QgMAQM5lVf3aeggAaOh/HJ0AAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAA
AABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYA
AAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgA
AAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQG
AAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZo
AAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKE
BgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBG
aAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABi
hAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAg
RmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAA
YoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAA
IEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAA
AGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAA
ACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAA
AABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYA
AAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgA
AAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQG
AAAAIEZoAAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZo
AAAAAGKEBgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKE
BgAAACBGaAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBG
aAAAAABihAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACBGaAAAAABi
hAYAAAAgRmgAAAAAYoQGAAAAIEZoAAAAAGKEBgAAACDmfesBAAB65Kqqxo1n
gHWcVtWn1kMA/SI0AACEDIajq9YzwLpm08lVVX1uPQfQH45OAADAARsMR+dV
9bX1HEB/CA0AAHDgxAYgSWgAAACWseG29RxA9wkNAADA0n3rAYDuExoAAACA
GKEBAAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAA
iBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAA
gBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAAgBihAQAA
AIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAAgBihAQAAAIgRGgAA
AIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEA
AACIERoAAACAGKEBAAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoA
AACAGKEBAAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEB
AAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEa
AAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAAgBih
AQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAAgBihAQAAAIgR
GgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAAgBihAQAAAIgRGgAAAIAY
oQEAAACIERoAAACAGKEBAAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACI
ERoAAACAGKEBAAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACA
GKEBAAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAA
iBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAA
gBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAAgBihAQAA
AIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAAgBihAQAAAIgRGgAA
AIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEA
AACIERoAAACAGKEBAAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoA
AACAGKEBAAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEB
AAAAiBEaAAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEa
AAAAgBihAQAAAIgRGgAAAIAYoQEAAACIERoAAACAGKEBAAAAiBEaAAAAgBih
Adim89YDAACrmU0nR1V10noOoPuEBmCbPs+mk6vWQwAAr1tEhnFVHTceBegB
oQHYNrEBAPbYo8jwS+NRgJ4QGoBdEBsAYA+JDMA2vG89AHAwPi/+x8xN60EA
gL+clcgAhAkNwC59WvwAAAA95egEAAAAECM0AAAAADFCAwAAABAjNAAAAAAx
QgMAAAAQIzQAAAAAMUIDAAAAECM0AAAAADFCAwAAABAjNAAAAAAxQgMAAAAQ
IzQAAAAAMUIDAAAAECM0AAAAADFCAwAAABAjNAAAAAAxQgMAAAAQIzQAAAAA
MUIDAAAAEPOuqk5aDwEAAAD0g9AAAAAAxDg6AQAAAMQIDQAAAECM0AAAAADE
CA0AAABAjNAAAAAAxAgNAAAAQIzQAAAAAMQIDQAAAECM0AAAAADECA0AAABA
jNAAAAAAxAgNAAAAQIzQAAAAAMQIDQAAAECM0AAAAADECA0AAABAjNAAAAAA
xAgNAAAAQIzQAAAAAMQIDQAAAECM0AAAAADECA0AAABAjNAAAAAAxAgNAAAA
QIzQAAAAAMQIDQAAAECM0AAAAADECA0AAABAjNAAAAAAxPx/e/d33MaR9Q34
+Ku9QBUuKEQgbgTSRiBsBOJGoHEEq43AdAQrR2AqgpUjWCiCFSN4yQggXqAK
d/ou0LApmiT+Naa7B89TxbIlkYNDcDg985vTPYIGAAAAIBtBAwAAAJCNoAEA
AADIRtAAAAAAZCNoAAAAALIRNAAAAADZCBoAAACAbAQNAAAAQDaCBgAAACAb
QQMAAACQjaABAAAAyEbQAAAAAGQjaAAAAACyETQAAAAA2QgaAAAAgGwEDQAA
AEA2ggYAAAAgG0EDAAAAkI2gAQAAAMhG0AAAAABkI2gAAAAAshE0AAAAANkI
GgAAAIBsBA0AAABANoIGAAAAIBtBAwAAAJCNoAEAAADIRtAAAAAAZCNoAAAA
ALIRNAAAAADZCBoAAACAbAQNAAAAQDaCBgAAACAbQQMAAACQjaABAAAAyEbQ
AAAAAGQjaAAAAACyETQAAAAA2QgaAAAAgGwEDQAAAEA2ggYAAAAgG0EDAAAA
kI2gAQAAAMhG0AAAAABkI2gAACJq0QQAACAASURBVAAAshE0AAAAANkIGgAA
AIBsBA0AAABANoIGAAAAIBtBAwAAAJCNoAEAAADIRtAAAAAAZCNoAAAAALIR
NAAAAADZCBoAAACAbAQNAAAAQDaCBgAAACAbQQMAAACQjaABAAAAyEbQAAAA
AGQjaAAAAACyETQAAAAA2QgaAAAAgGwEDQAAAEA2ggYAAAAgG0EDAAAAkI2g
AQAAAMhG0AAAAABkI2gAAAAAshE0AAAAANkIGgAAAIBsBA0AAABANoIGAAAA
IBtBAwAAAJCNoAEAAADIRtAAAAAAZCNoAAAAALIRNAAAAADZCBoAAACAbAQN
AAAAQDaCBgAAACAbQQMAAACQjaABAAAAyEbQAAAAAGQjaAAAAAByuRE0AAAA
ALkIGgAAAIB8BA0AAABANoIGAAAAIBdTJwAAAIA8RuOJoAEAAADIR9AAAAAA
5HAdIWgAAAAA8vgaIWgAAAAA8vgSIWgAAAAA8tDRAAAAAGQzixA0AAAAAHno
aAAAAADyGI0n1mgAAAAAsvi8/h9BAwAAAHCom/X/CBoAAACAQ31Z/4+gAQAA
ADjUbP0/ggYAAADgIOuFICMEDQAAAMBhPt//g6ABAAAAOMTs/h8EDQAAAMAh
Zvf/IGgAAAAA9jYaT2b3/yxoAAAAAPb128O/EDQAAAAA+5o9/AtBAwAAALCv
Tw//QtAAAAAA7ON6NJ7cPPxLQQMAAACwj9ljfyloAAAAAPZx9dhfChoAAACA
XV2PxpMvj/2DoAEAAADY1dVT/yBoAAAAAHb1p6dNrAkaAAAAgF389tjTJtYE
DQAAAMAunuxmiBA0AAAAANu7G40nV899gqABAAAA2NaHTZ8gaAAAAAC2dbXp
EwQNAAAAwDY+PrcI5JqgAQAAANjGxmkTEYIGAAAAYLPPo/HkyzafKGgAAAAA
Nrnc9hMFDQAAAMBzPo/Gk9m2nyxoAAAAAJ5zucsnCxoAAACAp+zUzRAhaAAA
AACedrnrFwgaAAAAgMd83LWbIULQAAAAADzucp8vEjQAAAAAD/08Gk9u9vlC
QQMAAABw321EfNj3iwUNAAAAwH3vR+PJ132/WNAAAAAArH0ejSefDtmAoAEA
AACIiLiLiO7QjQgaAAAAgIiIy30XgLxP0AAAAAB8Ho0ney8AeZ+gAQAAAE5b
likTa4IGAAAAOG1ZpkysCRoAAADgdP2Wa8rEmqABAAAATtNtZJwysSZoAAAA
gNPUjcaTr7k3KmgAAACA0/Ov0XgyO8aGBQ0AAABwWrKvy3CfoAEAAABOx3Uc
YV2G+wQNAAAAcBru4kjrMtwnaAAAAIDTcDEaT74c+0UEDQAAADB8Px5r8ceH
BA0AAAAwbL+MxpOrvl5M0AAAAADD9XE0nrzv8wUFDQAAADBMv43Gk67vFxU0
AAAAwPAc/TGWTxE0AAAAwLBcR8T02I+xfIqgAQAAAIajaMgQIWgAAACAoSge
MkQIGgAAAGAIqggZIgQNAAAA0LpqQoYIQQMAAAC0rKqQISLiL6ULAAAAAPby
cTSedKWLeEhHAwAAALSnypAhQtAAAAAArflXrSFDhKkTAAAA0Iq7iHg/Gk+u
ShfyHEEDAAAA1O8uVos+fildyCamTgAAAEDdriPivIWQIUJHAwAAANSs2kUf
n6KjAQAAAOr0Y2shQ4SOBgAAAKjNbURctDJV4iEdDQAAAFCP3yLidashQ4SO
BgAAAKhBE4+u3IagAQAAAMq6jtVUiZvSheRg6gQAAACU8/NoPHk9lJAhYtXR
0Oy8DwAAAGjUdUR0La/F8JS/RMTX0kUAAADACfl5NJ5cli7iWH749u1bLBfz
b6ULAQAAgIH7HKsuhpvShRyTxSABAADguAbzRIltrBeD/Fy0CgAAABimXyLi
/FRChggdDQAAAHAMJzFN4jHrjoZZySIAAABgIG4j4u+j8WR6iiFDxB8dDZ48
AQAAAPu7jYjLU5oi8ZR10DC453YCAABAD+4i4sOQH1e5Kx0NAAAAsLu7iPgQ
q5DBNfU9P3z79i0iIpaL+bfCtQAAAEDtbiPiKgQMT7r/1Im7iDgrVQgAAABU
zBoMW/p/9/7fOg0AAADwvc8R8Y/ReHIuZNjO/Y6Gm4h4U6gOAAAAqMnHWE2P
cFN+Rw+DBgAAADhVt7Fa4PHK+gv7EzQAAABwyu4i4lOswoVZ4VoGQdAAAADA
Kfocq6dHfNK9kNf9oMG8EwAAAIbsOv4IF27KljJcP3z79u33PywX82/PfC4A
AAC0RrjQs788+PN1RLwqUQgAAABkcBcRs1itu2BaRAEPgwY/AAAAAFrzOVbh
wsyCjuU9DBq+RMSbEoUAAADAltbBwpdYhQtumlfksaDhc0S8joiz/ssBAACA
71zH6lr1S0R80bFQv+8Wg3xouZifR8R5RLyIVfgQ6b8v0t+/PGp1AAAAnIq7
+CNQuAmhQrOeDRq2sVzMnwohztPfmYoBAABAxKqDPmIVJnxd/1egMCwHBw3b
Wi7mj4UQ015eHAAAYOUmfXA86wBh7Ys1FE5Lb0EDAAAAMHz/r3QBAAAAwHAI
GgAAAIBsBA0AAABANoIGAAAAIBtBAwAAAJCNoAEAAADIRtAAAAAAZCNoAAAA
ALIRNAAAAADZCBoAAACAbAQNAAAAQDaCBgAAACAbQQMAAACQjaABAAAAyEbQ
AAAAAGQjaAAAAACyETQAAAAA2QgaAAAAgGwEDQAAAEA2ggYAAAAgG0EDAAAA
kI2gAQAAAMhG0AAAAABkI2gAAAAAshE0AAAAANkIGgAAAIBsBA0AAABANoIG
AAAAIBtBAwAAAJCNoAEAAADIRtAAAAAAZCNoAAAAALIRNAAAAADZCBoAAACA
bAQNAAAAQDaCBgAAACAbQQMAAACQjaABAAAAyEbQAAAAAGQjaAAAAACyETQA
AAAA2QgaAAAAgGwEDQAAAEA2ggYAAAAgG0EDAAAAkI2gAQAAAMhG0AAAAABk
I2gAAAAAshE0AAAAANkIGgAAAIBsBA0AAABANoIGAAAAIBtBAwAAAJCNoAEA
AADIRtAAAAAAZCNoAAAAALIRNAAAAADZCBoAAACAbAQNAAAAQDaCBgAAACAb
QQMAAACQjaABAAAAyEbQAAAAAGQjaAAAAACyETQAAAAA2QgaAAAAgGwEDQAA
AEA2ggYAAAAgG0EDAAAAkI2gAQAAAMhG0AAAAABkI2gAAAAAshE0AAAAANkI
GgAAAIBsBA0AAABANoIGAAAAIBtBAwAAAJCNoAEAAADIRtAAAAAAZCNoAAAA
ALIRNAAAAADZ/KV0AbVaLuYvIuJ1+uP03j9N//TJ25k98v83o/HkZs/tcWKW
i/l5RJynP07v/dM09jN75P+/jMaTr3tuDwAAIH749u1b6RqKShdvr+99vIiI
Nz2XcR0RX2N1sXcTq4u9Lz3XQCWWi/l6XzyPVYjwIiJe9VzGdaR9cf0hFAMA
ALZxckFDuoib3vs4K1jOJp9jFT58iYiZO83DkzpnprEKFqbRf8i1i7tI+2Ks
9sdZ0WoAAIAqDT5oSB0L04i4iPqDhU2uI+JTRHzS8dCuFHZdpI++OxVy+xyr
fXJmn2TIHkyng4gDppotF/Np5lpOhel9UJjj106+nvL58SCDhhQuXEREF+1f
yD3lNlYXeFenvAO3YrmYr4OFi2g77HqOfbJSy8V8FpV3y4zGkxeli3hOOrH6
b+k6qMrf9+3sWi7mwzv5Km89DTVi1X33NVZTAG9CQFEt41N7HL+yWXcKR6yO
V+v/n8VAAopBBQ3LxbyL1YXc28Kl9O02Iq5idYF3U7YU1lLnQherffJl2Wp6
Z5+sRApe/690HVv4x2g8+VS6iKcIGniEoKE9n+P7tYeaP5FvmfGpTY5fvbq/
ZtosGgtNmw8a0kGqi4j3Mdw7xbv4LSI+mD9fTgq8uqg7oe+TfbKg5WL+PiL+
XbqOLfw2Gk8uShfxFEEDjxA0tO8u0rpDsZqWelOymFNjfGqT41dx1/HHcavq
NfyaDRpSwHAZEe/KVlKt24i4HI0nV6ULOQVp/vb7WAUMp9a9sC37ZAHLxfwm
2tknJ7UOmIIGHiFoGJ7rWHXjCR16YHxqk+NXdX6LP9bwq2of/X+lC9jVcjE/
Xy7mV7FqtRIyPO1lRPy6XMxv0h12jmC5mL9YLuaXsWpr+inaGTBLsE/2LE3f
aWmfdMcIKOlVrO6w/99yMZ8Zq47H+ATZvI2IXyNivlzMP9V03GomaBAw7O3+
xZ2DZCaPBAym7WxP4NCfrnQBO3pfugCA5E38MVZdps5F8ulKF7Aj4xMteBur
49bXGo5bTQQN6YLuSwgYDvEyIv6TEnqPaDtAujj+EgKGQ60Dhy8elXQ0rYWL
r9K0OIBavIzVeH+T1hQgD+MTHM9ZrI5b8+ViflVq3606aFgu5tM0f8sFXT5v
IuJ/y8X8Q+mUqzXLxfx1egzTr9FWu1/tXkXEf1O7l30yk9TB1OJ+2pUuAOAR
ZxHx79ThMC1dTMuMT9Crd7GaDtb7tV+VQUNqS/8Qq4W3WjwQteCfEeFO8pZS
V83/wpMkjultuGOUU2t3i9a60gUAPONlrMJxN2z2Z3yC/v0zej7Pri5oSBe+
X2L1ZnBcvw+WpQupVepiWE+T4PjWd4xmWhT3l05+Wz2Re2l6F9CAf0aE6ag7
Mj5BUb2eZ1cVNKS7xroY+vfPNE/+vHQhNUmJ3/9i1dpPv97EquOm1ZOR0i6i
7elmXekCALbwKlZhQ1e6kIYYn6C89Xn2Ubsbqgga0lSJWbhrXNKrcGEXEb/v
j59i9YgryjmL1QKmOm521/rvcVe6AIAtncVqYeOudCGNMD5BHdbdDVfHmgZW
PGhILUhfwtz3Gqwv7E52jvy9/fFt6Vr43brjxlzYLaTOpNb33zOhJ9AYYcMG
xieo0rtYdWZlP88uGjSk9RhmYapEbf69XMyvShfRtzRwzML+WKNXsVrAxtzI
zYZyAjSU7wM4HcKG5w3luD6U7wPWjnKeXSxoSAfi/0bb87SG7N0phQ1pf/xP
2B9rdharxNUA/7yudAGZvNPFAjToV0/0elJXuoBMjE8M0fo8O1vYUCRoSBd1
v5Z4bXbyLq1KOuiDaVoDwP7YhvX0nq50ITVKg8OQFi8VKgEt+jT0c6ddGZ+g
CVnDht6DBiFDc97EajrBIKWuDY9SbY/21Md1pQvIrCtdAMAeziLiU+kiKtOV
LiCzrnQBcCTrsOHgsLTXoEHI0KxXQ5xGkb6nd6XrYG/Chj8b2h2WNx67CzTq
zSkvrv0I4xO0I0vY0FvQIGRo3qDWbBAyDIawIUlrVwxxIdOhnZwCp+PSFArj
EzTqVUQc9Ij5XoKGdIARMrTv3XIxvyxdxKHS9yBkGA5hw8pQT3i60gUA7Oks
DjxRHwjjE7Tp3SHn2EcPGtJiElfHfh1681PLF3Wp9p9K10F2J73Kd7pjNtQT
uVceawo07N0pt9gbn6B5H/Y9hh01aEgHl1l4ZODQfGjxwJouRHXWDNenFvfL
TC5i2MfZrnQBAAe4LF1AQcYnaNtZ7Nk0cOyOhlkM++Byqs4i4qqleYfpAtQK
0MN2Fqf7SLGh3i1aG/r3BwzbxYmOTRHDP34P/fuDiNXipzvv60cLGpaL+YcY
1vNy+d7BC4T0JQ3uVyH0OgUv48QCpbR/vy1dx5G93GeAA6jEWZzgBanxCQZl
5+u+owQN6Rfun8fYNlV518jB9SqEXqfkzRAWLd1BV7qAnrRwrAF4yik+6rIr
XUBPjE+cgpe7rtOXPWi4d/eY01D1FIr0DOuhp+n82U8ntDhkV7qAnjiRA1r2
6gQXhexKF9AT4xOn4nKXTz5GR8On0KJ+Sqp9dFNal+GydB0UM/j1GtJJ66l0
65y1/MQbgIiYli6gL8YnGKSduhqyBg3phd/k3CZNeFfp3eOrEHqdsr1XyW3I
qbXiumsEtOyUjmHGJximbttPzBY0pDuHVd7ZphdV/ezTHP1TSdJ52ttG1hHZ
15C/t8e8HXqXCjBo09IF9Mj4BMP0ZttpYH/J+KIfYth3jz9HxE36+BIRX9Pf
fx2NJ1/Wn/Tgzv6LiHgdEefpY8jdHq+Wi3k3Gk+uSheSdv6fStfRg+v4fn/8
cu/fvozGk68Rv4eAr+/92+v4ft8ceiBztVzMz9fvx1CkY83L0nUU0EVlwSbA
ls7SeHRTupBjMj7B4HWxxfT0LEFDOqC8y7GtilzHar2J2Wg8mW37RY987neP
2kvrBkzTx9AWKbxcLuafKriguyr8+sfyOSJmsfs++TV93dqfvjb9Dk9jdQdi
aMHDeh2RrnAduXWlCyikCydyQLtex+omwZB1pQsopAvjE6fhIrYIGn749u3b
wa+0XMy/xDAuTm5jdYD41EfanO40X8TqwDSUboefR+PJZakXT23y/yn1+kdw
HX/sk70EOKkjZL1fDuH3eu3vuwQ0tVsu5l9j2F1kz/lr33cEUxj33z5fk+rt
fUxZLuaHn3zRqqLnSX0wPg2+Y8Xxi4gt9vWDOxrSApCtX4zcRsRl323/6cLx
KlJrd6ySodY7Q7oo9KSHga0T8jEiPtyfltOXdND4EBEf0sVVF+3vlxGr/XJa
uIYs0nH3VE/iIlaLjPW90NjXWHUVtaj2ILvV97V0994xlfqZnMfwW+7PSxdw
TManIuMT3yt1/Kp9rM3tIjZcdx3c0bBczG+i3UHhLiLe17CuwFoKHK6i7Z31
xxLvaVoAsvW1GT7GKvS6KV3IfQPZLyMK7Zu5LRfzTzG8qVe7uB2NJ+eli2hF
7XefRuPJD6Vr6JufyWZp3DmP1VSD9bTTVs837/s8Gk+mpYs4FuPT8Mcnx6/N
0lT5F7E6bp3H6hjW+o35h34bjSfPLvp6UNCQUstf995AWR9jFTJUeUciTQG4
ijZT4d4Psqmb4SbafL8iVl01Xe2t/Wm//BDtnuw1fwKQ9vV56Toq8LcSHT8t
clJYHz+T/aST9y59NDvetz4OPcX49LtBj0+OX/u5N2X+IoYRxt2NxpNnn7Ry
6OMtLw/8+hLuYnVXs6s1ZIiIGI0nn2KVfl2XrmUPLx88faMP76Pdk45fIuJ1
7SFDxHf75cfStezpZQpIW9aVLqASWlPhxIzGky+j8eR9rO4Q/hyrc7rWtBrU
b6MrXUAljE/8yWg8+ToaT65SF8Bfo91j2NrZpsdc7h00pJP11g6WdxExbaV1
OrXPT6PNi7reDrIpIWzxoH4XEf8YjSfVdtY8Jh0ou4j4sXQte7osXcCButIF
RB0D46k9ox1I0jh0Ge3ekBmqrnQBYXyiAaPx5CYdw86jzeu8tfPn/vGQjobL
A762hOuIOG+tleneRV1rO+HbFAD0ocVuhnXo9WnjZ1YqBXZ/izoG9V0029WQ
kuMa5vhdli4gVkm6kzk4YfduyAgbCjM+fcf4xFbuXef9I9o7n47YsMj6XkFD
+uVpqZvhOlYXdc3cNX6o0bChO/YLNNrNsA4Zmgq9HpO+h2m0d3C8LF3AnrrS
BSRXUceJfVe6AKCsdG43jdVaR5TTlS4guQrjE41JNx6n0d759Plz/7hvR0NL
F3Z3EXHRcshwz/uo4+C5ra6H17iItroZBhMyrDUaNrTa1dCVLiBWqwyvH81b
Wp+dU0Cl0jGpK13HietKFxDGJxrW6Pn0+XP/uHPQkFqjWnrE3bS2RwXuKx08
L6KdHfDVpkVCMrg88vZzGlzIsHbv4NiSrnQBu0irrdfQSbae7jMrWcQ92lOB
SAsqfy5dxykyPj3J+MRO0vl0V7qOHWR/6kRL3Qz/GtpFXQpNusJl7OJoB9n0
ZIsaBrZtdUPbH+9L31tLC0S+SSdHrajl2DuL+P3nXUOrci3vC1Deh9IFnKha
jsOzCOMTbUvTKH4rXceWnl2XZZ+goduvjt59Ho0ngxxwGtsBp0fcdnfEbef2
S8sLP24rLRDZ0loiLZ0E1HBn5PpBh1gN+3QfnVNAA9I420rX55AYnx5nfGJf
LZ2fPmmnoCEtAtnCfPi7aOsidB/vo43B9O0xNprmvb07xraP4Do99/tUvI86
7iRso4aTo40qOvZePfhzDSdyEY38HIFe1HJcOgnGp42MT+wshWYt3bh71K4d
Dd0xijiCD0NZl+Ep6ftromMjTXHIrTvCNo+lK11AnxpblOuskUUhu9IFJLP7
f0hzomsIPE8pyAOeV/sUxRqOmTl1pQtIZvf/YHxiAK5KF3CorYOGdAf5KHen
M7sdjSeXpYvoyYeo4yC6yfQI2+yOsM1j+HnI6zI8JQ3wrSSxVd9tqOjYe/vE
vlzDXaOXja23ARxP7WNu7fVtzfi0FeMTe6koLNvbLh0NVZ+M33NZuoC+VPQI
n02yHmDTfLdnFx+pxF000nVyJM1M76n8EVS1HHufOmGb9VnEM7rSBQBsYQiP
W18zPm2nK10AzZqVLuAQuwQN02MVkdFtWozulLRwITvNvL1aBrZNLlMYdJLS
997C/hlR9z5VS9vlUydyNdwxinAiB6zclC5gg8F0NITxaVtd6QJoVtPHi6F1
NFyWLqBvaa2G2p8bfZb5jnGXcVvHcjvUp57sqJXpPVUe3yrq3rlLLXx/kgKl
Gp6Cc5YWJQNOWANrdDV94bBmfNqJ8Yl9NX282CpoSIv51bCi7HPuop7ksm9X
pQvYQpbpEymwqGFg2+SqdAE1aKirodbpE13pApJNx9ZZH0VswYkcnLgG5sPP
SheQSVe6gMT4xJA13Rm9bUdDC78cVyfcpt5CwJJr4G9hXzz1tRkeuipdwJam
pQt4RFe6gGS24d9rOQZdVBoYAf2p+RhwPaBz1a50Aclsw78bn6CQbYOG6TGL
yOSqdAGlpEGr9ukTuQ6u00zbOaZPAzqROFhDzwKeli7gvnRX7mXpOpJnT9TS
z/i6n1KedRZthJHA8dR8MTcrXUAOxqe9GJ/Y2VPTgiry7O/WXzZ9dSOt6ten
+AjBBy6jsgulB24ybWeaaTvHpJvhzz5FxLvSRWxwEfUsbBVRTy2/bRmcfYo6
xoqLOOHgGcj7pKvMrkoXkInxaT/GJ3bSQBfMs79/G4OGaOPCrpa2qGJS4jUr
XMZRpYWHaknQn/LUs5xP2mg8+bRczG+j7p/fy+Vifl7RQmK13PmYbfl5nyLi
pyPWsa23lf0cgX7VGjQM6fzA+LQf4xO7qvV4tnbz3D9uM3Wi9m8wQtBwKqal
C9iCffFpLbw309IFRESk1alrWYB3q59bOoG+PXIt26rlJBjoUbr797Z0HU+4
Kl1ADsangxmfGJKb5/5xm6BhmqWM4xlSQszzpqUL2MJV6QIq1kLQUEuwWsuJ
yPWOd15q+Rl3pQsAiqjl2PmYoUyrrOU9Nj5xCs5LF7DB7Ll/3CZoeJOnjqOZ
lS6A3tRyEfgUodcz0vSeu9J1bDAtXUC6I1fLeha7npjNjlHEHl418Ig7IL/L
0gU84eMQFok2PmVhfGIX56UL2ODZ655ng4ZGfhFmpQugNzUs5POcWekCGjAr
XcAGNexjtdwtitjxRG40nnyKesKkrnQBQH+Wi/n7qHMdoLuoNwDZlfEpj650
ATRjWrqAZ2x8XO+mjobzfLUczax0ARzfcjGflq5hC7PSBTRgVrqATSrY17rC
r7+2b4dOLe2pNZ0QA0eUboz9u3QdT/gwoMX/utIFJMYnBi91ENU8s2C26RM2
BQ21dzTcDejgzfNq3xcjGriIrsCsdAFbKLavpSer1DKo7HtCNstZxAFeVhAa
AUeWQoZZ6TqecBsDWZvB+JSV8Ylt1B5IzTZ9QutBg/nwp6P2fVHotYV0B6KW
1sWnnBd87ZoGldmeX1fLHaOIeu6+AUeQpkvMop6nIDzUDWFthsT4lFdXugCq
15Uu4Bl3aTrSs1qfOjErXQC9OS9dwAZCr+3V/l6VDLXeF3zt+7YaQB6TTqo/
Z65nXzWdGAOZLBfz6XIxn8VqukStIcPPaRHkoTA+5WV84kmp46WWDqLHbPU7
uCloqGFhtOfclC6A3tTe0TArXUBDZqUL2KDIvpbaf2tZyOzQuz613DU6Wy7m
XekigMMtF/PXy8X8/XIx/xIR/426T8I/jsaTy9JF5GJ8OgrjE8+pfcrVVvX9
5al/SHOxandTugB6U+sdi7Xa79LXpPb3qtS+1hV63cfMDvz6T1HPwmwXEXFV
ugjgeeli9sW9v1r/eZr+v/bzgLXrqOfufy5d6QLumR349cYnqrZczC+j7pv9
19suxvpk0BD1t6rHwFrSeEIjC+bclC6gIdXPV10u5tMCx5eu59d7zkF3fEbj
yc1yMb+OOgbKt8vF/MWA5knD0S0X82+la2jUdURMB3i86UoXcI/xicFKXS4/
la5jg627LZ6bOnF+eB1HVfuCcpyQPR+zdJIEhH+2XMwvop67dZ8znfTMMmwj
l650AcDgDTJkMD4dXVe6AOqQQoZfS9exwe1oPLna9pNbDhpc2J2OaekCNrgt
XUCDag8Kpz2/Xk2LQuWav3qVaTs5dKULAAbt42g8eT20kCExPh1XV7oAylou
5i+Wi/mHqD9kiNhxWtimxSCBzW5KF9AgQWGyXMxfRMS70nXck+VELnX51BLC
vWpk3SGgPT+OxpOudBHHYHzqhfHphKWOoS8R8c/StWzh865PfHkuaJgeVsvR
zUoXQG9qf+LEEO9gHFvt71mf+1xNd4uuR+PJTcbtzTJu61Bd6QKAQbmOiL/t
0kbcIONTP7rSBdCf1MHQpSfo/CfqeaLLJt2uX6CjgRa82PwpRbk7v7va37M+
97maTuRmmbdXy2PEIpzIAXncRcTPaapE7WPZobrSBdwzy7w94xO9WS7m5ylc
uIpVJ/SvUceCpNv61z5B33NPnQDgiFK75NvSddxzlXNjo/Hk03Ixv4s6FhJ7
uVzMT+HCADiejxHxfqBrMXwnjU9vStdxz1XOjRmfyOmRJ+RN7/23pcfzPubz
aDzZ+kkT9z0XNNTerj4rXQC9OS9dwAY3pQto0E3pAjY4ECFYIgAAHFVJREFU
7+l1aupmuD3SSc4s6glT3oc7R8DuPkbEZebW/doZn/plfMrE43mzuo0DjgXP
TZ1oOXlhWGqfu3RTuoAG3ZQuYIO+9rmup9fZxuxI262pPbWmE2egbrcR8XNE
TEbjSXdiIUOE8alvxidqcxcRF4d0cFmjAaCA5WL+Ouqan3esE66aTuTO0grP
AE/5LSL+MRpPzkfjyeUpTJN4yPhUhPGJmtxFxPTQTiJrNBzBcjGfRV3z2qoy
Gk9+KF0DVKArXcA9d7s+smhbo/Hk63Ix/xz1HBMvoq6TS6AubyPi9XIx72J1
J312gnPnu9IF3GN8gn5lCRkidDQAlFLTnYvZkbdf04nTu/RseICnvIxV4PDv
iPjfcjG/WS7mH9Kd/lNgfCrD+ERp2UKGCEEDQO9Se2RNa48c+0SrphO5iLpO
ooH6vYyIf8YfocPlUC8IjU/FGZ8o5Toisj79pNmgYTSezErXAMmptVTmcOrv
WW0nEkc90UqLqN0e8zV21JUuAGjWy4j4KSLmy8X8Kj0GckiMT2V1pQvgJH2M
VSfDTc6NNhs0QC1OcaGoQ53ye5bugtV0Ive5p59HTXeN3gzw4gDo37uI+L80
raL5DgfjUxWMT/TpLlaL33bH+F0TNAD06yLqenxwXydYVz29zrZqOpkG2vbP
iLhZLubvSxdyIONTHYxP9OFjRJwfa7HVCEEDUMAQ7vwcoLYTiF5O5NKcv7s+
XmtLrV8QAHU5i4h/LxfzWcNjnPGpDsYnjulzRPztWF0M9zUbNCwX82npGiDC
vrinU1m5+zupHfJt6Truuc09H2+DmtpTX57QCvJAf97EqrthWrqQXRifjE8M
3ueI+PtoPMn2VIlNmg0aABp0kneLCr7eJl3pAoBBOouI/y4X8650ITswPtWl
K10Ag3AXqykSf0sBw6zPFxc0APSnK13AA1d9vtgx5wHuqbYTa2BYfm0obOhK
F/DAVZ8vZnxiYH6LiB9jtQZD11cHw0OCBoAepDbIV6XruOeu0MDzW4HXfMrL
9Mx4gGOpPmwwPv3O+ESr1p0LP0bEZDSeXIzGk6vST3kTNAD0oytdwAOl7t64
awScmtrDhq50AQ8Yn1aMT2xyHRH/Go0nL1LnQvFw4b7ngoaaVl/ltNW+L56X
LqBB56UL2OD2CNus7YTBidzKRcMrxAPt+LXiBSKNT2Vf9ynGJzZ5Faun3Xxb
LuZflov5ZU0LiT4XNBSZy7GDaekC6E3t++J56QIadF66gA1ucm4snVy+zLnN
Q5Waj5qS9usSr/2Es6jvJBsYpk+1XTgan757XeMTLXsVET9FxP+Wi/lNCh2K
Hm/+UvLFAU5EV7qAB0rPQ72KiH8XruG+i+h54TGo3M+FXvdF/Pnxx+dR2YXw
Ac5iddd8WriO+7rSBTxgfPqe8Yl9vIxV6PDTcjH/GBGXPT8uNiIEDbShmrlG
TzgvXUCDqmnrekLufa62OxKl20NnhV//obfLxfy8xCAMNRqNJ5ela3go3Zl7
Hasx93WsLtZrWsBwW2+Wi3k3Gk+uSheSGJ++Nyv8+g8ZnzjUu1hNw/kQER/6
XMPhuakTs76K2NO0dAH0xtSJ4amqdfQR2fa5tADYWa7tZVL0RC6tJn6MdTAO
UdvJNnDPaDz5OhpPZmmxs/ej8eR1RPw1Vqus19Tuvo0PpVuaI4xPjzE+MVBn
sepw+NLnWjGeOgGHOy9dQIPOSxfQo9pOEK4rWZG49F2rh7rSBQC7GY0nNyl4
eB0Rf4+Iz6Vr2tJZRLwvXUQYn55ifGKoXkbEf5eL+WUfL/Zc0HDTRwEHqL31
mnxq72gYytzRPtX+ns1ybCTdsXqbY1sZXZUuIKntRO7VcjE/L10EsJ/U7TCN
iH9E/U+rioh4X7Krwfj0LOMTQ/fTcjG/OvaLtBw01NbqxfHUkG4/ywCwvZoe
u9ODrnQBj6jiBGo0nsyivouBGu4wAgdITyyYRv3TKUp3NXQFX/spxqenGZ/I
7V16JObRAs+Wg4boc44JRdXe0RBxWlMBDnVeuoBN0klGDl2m7eRyW9mCUlWc
VN5TWxsxsIc0z34a9c21f0jQ8Afj0/OMTxzDqzjiuoxPPnViNJ7cLBfzY71u
LuelC+D4RuPJ1wb2xWnUv4BqLWrvaMhyFyN1udS2IvrXvublban4YmgPvFwu
5tOMQRNQSDp3uIiI/5Wu5RlnJZ5AYXzaivGJU/FquZhfjcaTLveGNz3e8jrq
OxDdd166AHrzOSLelC7iGbVfPNek9vcqVwdNjW2Or6LuY3oNuhAawiCMxpMv
y8X851ittl6ri+h/bQLjU5u6MD5xHO+Wi/lN7kcbb3rqRO1z46elC6A3N6UL
2KD2i+ea1P5e3WTajjbHNvm5wbB8iPrm29/3tsCikI5zbfJz45h+yr0swaag
YZbzxY6g9gsW8rkpXcAGL2t4JnbtUrtm7U+cOLijIR2oa/8+edxZarcGBiA9
LvGqdB0b9HbMMT41zfjEsX3KeT2zKWi4yfVCR3Jmtf+TMStdwBampQtowLR0
AVvIMXWiy7ANyulKFwBkdVW6gA2mPb5W1+NrkV9XugAG7SxWXWBZbAoaWljt
f1q6AHphXxyGaekCtpBjX3PHoW0lWpmBI0lPoaj5CRTTHl/L+NQ24xPH9i7X
FIpng4Z0YK7dtHQBHF9qfaz5JCHC4L2NaekCNrhO+9relot5F6tEmLb5fYZh
qfmc9mUfHbrGp8EwPnFsWboaNnU0RKxW+6/ZtHQB9Kbmk4SInk4UWrVczF9H
/fNCdTOwVuOq7MD+aj+HOO/hNYxPw2B84thepWDyIJsebxmxOjDX/FjBl8vF
/HVN3Rej8WRa4nWXi/n7iPh3idfuySwi3pYuYoOLyDi3aWBaOMGZHfLFqZ2x
9n2U7bxaLubno/HkpnQhQBbVnCc+YRpHXI/K+DQoxqfn9XWT/HUMu0PoMg5c
32aboGEWEf885EV60IV0LyJi6HO2ZqUL2EIXgoandKUL2MLswK9vIUxhe12s
BlqgfbU/sv38yNs3Pg1LF8anR5W44ZvWNDiPVfhwEfV38G7j5XIx70bjydW+
G9hm6kTtCXCEg+dJSF0rNT8LOyKlzKWLqE0j0yZuM9wdEHgOS1e6AOBknB95
+8anYelKF8AfRuPJbDSeXI3Gk/ej8eQ8Iv4aEb9E/dctm3SHfPHGoCGdeNe+
CN/LdCFz6qalC+jBrHQBW+hKF1ChFk5wZod8cQqYXmWphFoYW2A4bkoXsMHR
ulKNT4NkfKrYaDy5GY0n72MVIP4c7QYObw65gbpNR0NEGxd3LVzIHNspHHA+
lS5gC13pAmqS5oW20HU0O/Druww1UJ+udAHA4RqYz37MIKA74rYppytdAM8b
jSdfR+PJZayu0Wp/wMJT9r7G3jZoaOHi7uKUnyub0qYhL0iyNitdwBZe5lip
dUAuoo1989DjXJejCKrTlS4AONyJ3/3tShfAUXSlC2A7qcNhGqvpFK3p9v3C
IXU0nEUbd02PZVq6gD6kOxLXpevYwmXpAipyWbqALVyPxpO9FwprZA0K9nO2
XMxPeWyBoTjJm1HGp0EzPjUmTaf4sXQdO9p7P9sqaEgn4C20e1yWLqCgUzrQ
tNBh89LBPyJ1drRwgnN14NebujVsJ/+7DDTL+DRsxqfGpKc4/Fy6jh0dL2hI
Wrm460oX0bc0beKUno3cwr4Y4TGXEe2Ef4fuUwb6YXt3ylPzYCDOSxdQiPFp
2IxPDUrrNvxWuo4dTPf5oqEFDRERlyf4C9eVLqBP6TGXtT8JJeJEg6+15WJ+
GW10M1wfskhY6lxpYQ0KDuNkHdp2XrqAvhmfTobxqU1dtHE9E7HnU062Dhoa
mhv/Mk6oTSyFKifz/d7TSrfAhxMMvtZdNq3sl4fuS12OIqheV7oA4CDT0gUU
0JUugF50pQtgd2lpglbOlSP2OIbu0tEQcfg85r78dMgzPxvzPk4zrW6lw+Ys
2vm9yekq2tkv996XUoh0StOWTtlBz5IGintTuoA+GZ9OivGpUaPx5FO0sQ5i
RA9BQysXdxEncHHX2F3jrFKHTSu/mG9PaWHI5WL+Pto5oft4yNMmQrviqfHz
hgad0hh8zyl+z6fMz7tdl6UL2NJ01y/YKWhIF3etLFzxJs0RH7KraOeu8TFc
lS5gB1en8Azv9D3+u3QdO7g68OtPMug7YV3pAoC9nOKx+hS/51PWlS6A/YzG
k1m0cfP0bNdrmV07GiLa6mr4aagpdmN3jY8iPR7mrnQdWzqLVdgw2PUa0vc2
K13HDm7TwX0vqaPoVbZqaMGrUwgMYUiWi/k0Tux8yfh0koxPbbsqXcCWjhs0
NHZxFzHAO8lp0GzprvExtbIoZMRq0J8NMWy4FzK01GFzeeDXDzLEZKOudAHA
Ti5LF7ClnHc0jU+nqStdAPtp6Pr66B0NEW1d3J3F6uJuEGFD+j5a6io5tpb2
xYhV2DCozoZ7IUNLd0/u4vDfI22pp8kJPDTihLs/jU+nyfjUthau73oJGq72
/LpSBhE2pPpn0dZd46NKC/l9LF3Hjt7GQDobGg0ZIiI+HLIIZPpdfJmxHtrx
cqhT8mBIlot5F211f97k2Ijx6aQZn9rWQtCwU3C7V9CQFoVs7eKu6bAhHThm
IWR4zGXpAvawnkZxXrqQfaXfpS/RXshwF4d3wnQZ6qBdTuSgYilk+LV0HTu6
ybSdLtN2aJPxqV2z0gVsY5drl307GiLaa1mPWF2k/y+10jUjPT3jPyFkeFSj
wVfE6gL9S4vpczqJm0Wbd00O6mZIuhyF0KzmfmfhFCwX8xfLxfxTtBcyRKyC
+xy6TNuhTcanRqVz0+vSdWzhfNtP3DtoGI0nX6KNR3E85t/Lxbz6u8nLxfx8
uZjPIuKn0rU04LJ0AXs6i4j/LBfzDy1MpXhwEtdi8HVwN0MKhlr83snnLIVt
QAXS+dJlrLoC3patZm83h27A+EQYn1o3K13AFraeHXBIR0NEuxd3Eas5Jl/S
wFSVdDF3Gat0+xQXMdpZw10Na/+MiJuaB4fUCXQT7Z7EReTpZnC3gAj7ARSV
woUuhd//F6ubMs1eZKcbeIdyXCLCftCyXJ1Nx7T1jdEfvn37dtArpTvurV8M
30bEZXq0SDHpjvZFrAKcFlvStzIaT344xnbT+3cTDZ9oJFXsj2sp/LiM9vfJ
24h4feAikC8iYp6vJBo3yRBcHd1yMT9soD+yY40JNfMz2V467r6O1cnt63sf
rY9J930ejSfTQzZgfOKBo41Pjl/Hk9Y/+1/pOjbY+nj1lwwv9j7qf0M2eRkR
vy4X8w+xaqu+SnfIe5GmcLyP1by61i+SixmNJ1/Tz7D1qSbr/fEyVk946XV/
jBjsPnk58G6Gf4zGkxZWLN5JagX+T+k6ntBFm+sVwbPSTaRSXkR7iwwfaujd
DMan/nVhfGrOaDz5slwMJy88uKMhImK5mF9FxLuDN1SX61hd5M0ytbN9JyVW
01gdCE5qQD120rhczG9iWHc6Ilb746eI+HSM/TEiYrmYT2O1T17E8PbJg+8W
RVTdwXU3Gk+qX+NjX8vF/GvUGXhdj8aT6p9k5O5TfWr/mdC7gy/EjU9lnOL4
VPvxq/UxZbmYV/9Et23f4xwdDRGrtuqhLUDzKtLzl5eL+V2s0uZZrFrzbyLi
y7Z3R9MF3Lrlb5r+O6T3qjZdRPy3dBGZvUofP6Wk83N8vz/ebNv1kLoV1h/r
FtQaT05y6g7dQHrfan2fBnen6IFPUWeY/Wq5mJ/33XEEDM7skC82PhVlfCK3
6qdkbitL0DAaT24G0rL+lLNYHcC/O4jfa225jT+vFlzrAX/wRuPJbLmYf4w6
D/y5PLc/roOx+0453Po500Bbc1vqrHQBRzaLen+f36cPgH1cD3xa36x0AUc2
C+MTec2i8uvI5WL+epsO60OfOvG70XhyGW08+/MYXsYfF35/ugCkiPexuuA+
RfeDsfXHqYYM1+nYlEPNg/Up3DGqVc0n+ED9rjJsw/hUTs3fn/GJY9lqOlS2
oCGp+UDHCUl3B7rSdVBcl2MjaU2VWtf9+K2FJx8cIn1/v5Wu4wkv0/4BsI9D
12YwPhVkfOIIbkoXkEvWoGE0nswi4pec24R9pYWV7I+n618ZF87sMm3nGGq+
m5JTzd+nkB3Yx+cMU/u6DHUcS83H7Zxq/j6NT+25KV3AFqbbfFLujoaI1cKQ
pzqFgsqMxpP3YX88Rb+NxpOcj3XqMm4rt1npAnoyK13AM7SnAvu4yrCNLsM2
jmVWuoCezEoX8AzjE8VkDxq0rFOhizjd9RpO0W1kPAal52TXusbF9amsKJ2+
z1pDw7O0nwBs63Y0nlwdsgHjUx2MT2R2U7qAXI7R0RCpXflfx9g27CoNAF3h
MujHXURcZJ4TWvMAfVW6gJ5dlS7gGV3pAoCm5Oi6Mz7V46p0Ac/oShfA9hoJ
6KbbfNJRgoaIiNS2XOviKJyYtF6D8Gv43mdclyGWi/mLqPtEbla6gJ7NShfw
jLdpfwHY5C4OvDA1PlVnVrqAZxifKOJoQUPSRb2tRJyYFH59LF0HR/OvQ9tQ
H1FzW+ptzlClBen7vS1dxzNqPukH6vE+Q+ed8akixif4s6MGDffWazA/vg53
EfG5dBEljcaTLnTaDNHHzIs/rtU8MNe8yvUx1fx9W90b2OQ6UyhufKpPzd+3
8Ymczrf5pGN3NKwTvumxX4etfIi6W7v60oVOmyH5mAKkrJaL+XlEvM293Yyu
ShdQyFXpAp7xKu03AE85+ILP+FStq9IFPMP41Jaau2MiIl5u80lHDxoifg8b
fuzjtXjS7Wg8uQxBw7rTZhrChiE4SsiQ1Hy36O7U2lLX0vddc5dczfsNUNYv
o/FklmE7NR9njE/1qnm/4Xs3pQvIoZegISIitYkJG8rp0n9vCtZQDWHDIBwz
ZIioe5Xmmtsz+1Dz9689FXjM9Wg8yXV86DJt5xhqPj73oebv3/hEr3oLGiKE
DQX9nqCnR6bUnLb2RtjQtKOGDMvF/HVEvDrW9jOo+USmDzV//y/T/gOwdheZ
wgHjU/Vq/v6NT2SzXMynmz6n16AhQthQwG1EXD74u5NsaXvMvbDB0yja8cuR
Oxki6r5btH5c68lq4PvvShcAVOUi43SCLtN2jqKB4/NRNfD9d6UL4HT0HjRE
CBt6dvHII5RmJQqp1Wg8+ZouXIUN9fsxY+vpc2qex+ipKSs1vw9d6QKAavyY
aV2GNeNT/Wp+H7rSBXA6igQNEcKGnvz4RIKuo+ERKWywT9bpLiL+numRYM9a
LuYXseVquoXUfrekLzW/D2dpPwJO2485xy3jUzNqfh+MT+SycRpOsaAh4vew
4W9hzYBj+OWZwU3Q8AT7ZJWuI+J15jtCz6l9AK75BKZPtb8Pte9HwHFlDRmS
2o8rtR+X+1L7+1D7fkQbi/e/2PQJRYOGiN8fBfM6LMiX08fn2svTgpA8Ie2T
5xHxuXAprAKz133ts8vF/EXUPQBfPzIV6iSl96Hm39GLtD8Bp+UuIv6RO2Qw
PrXD+EQGN6UL2EL9QUPE7xe+0zBHPodtV+Ov+QBYXFq3YRoR/wrdDSWsT9T6
fhTTRUSc9fyau7gqXUBlar5rdBZ1XxQA+V1HxPRICwIan9pifGLo6p46cd+9
Bfl+DBd2+9rlkX+mT2xhNJ58CI/A7NtvEXFeaOXm2gfemk9cSqj9/ah9fwLy
+RirkOFY51e1H09qPx73rfb3o/b9ifq10dFwX2o1ex3uuO9q10f+CRq2NBpP
vozGk9ehu+HYbmPVxfDYk1KObrmYn0fE275fdwfXpj19L70fNYeAb9N+BQzX
euzqjjV2GZ/aY3ziQC1MQ3q16ROqCxoiVr+c2ta3dhf7PfJP0LCj1N1wHqb4
HMPPsVrwseQdgNrT/VnpAio1K13ABrXvV8D++hq7aj+OzEoXUKlZ6QI2qH2/
OmVNXKctF/Nnp09UGTSspQu711H382hLWs8FvNr1C4/Y2jdo96b4/D103eTw
MSL+OhpPLitYRKor/PqbXJUuoFJXpQvYoCtdAJBd32NX18NrHOKqdAGVuipd
wAZd6QJoXrtBQ8Tv3Q0Xsbqwq7kFqW+/xOFzAb2fexqNJ7PUdSNw2M/niPhb
ajW9KV1Mah/c2AJW0K1w8HHpfbktXcczXm1K/IFmrAOG3sYu41O7jE/sq8dH
uh/q2a6Y6oOGtXRh9zpWi0XW/Et7bLcR8ffRePI+Q4puYDiQwGFnH2MVMBxz
wax99P10i13NShdQuVnpAjboShcA7O02VlN5J4XCceNT22alC9igK10AT2rh
evftc49KbSZoWBuNJ1ej8eQ8Ti9wuIuIf43Gk/OMKVdNF3pNuxc4/C2s4fDQ
Xaw6cNZ3gWrc72qfp1j76tWl1f7+1L5/Ad+7jdW49bd03vWh4PS+2o8ftR9/
S6v9/al9/zplNZ4vP+byqX/44du3bz3Wkd9yMZ/GKu2teTXeQ9xFxIeIyD7I
pffuvzm3uY3RePJD36/Zt5Tudemj5pbHY/ocEVf7rCHSp1K/Bzu4G40nGx8h
dOqWi/nXqPsZ838v1Qq5XMyrHuhPYUx4qPafyQm6i9Wd51lEzGoJxI1PwzC0
8an249dQxpTlYt5FxK+l69jSx8eefthcR8ND6U7yRUT8NVar/w6ly+E2Vl0b
58dabKih+T/NSYtGfkjTff4WqzsjQ9k3n3MdqxbTv6bpEVeF69lGV7qADWq/
G1KL2t+nrnQBwO8+x2pc/jFWXQsv0qOVP9QSMiRd6QI2qP24W4va36eudAE8
6lO08/TFd4/95V/6ruJY0py5y4i4TAubdLFqB3pZrqqd3cVqp+pzoLuO073j
3ov0s3wfEe/TvnmRPobyvn+O1X77qYaFHfdQe9vgrHQBjZjFEwNdJWrfz2Ao
biPiJv3/l1g9j/5m/dHYOFX7cWNWuoBGzML4xI5G48nX5WL+PtrpaviT5qdO
bJIu7Kax+iV6U7aaR93G6iJt1sNzmKlIml4xvffRSvDwOVYnb/ZZAADgTwYf
NDyU5ru9vvfR98XddaySzfWF2k3Pr0/FHuyf51E+HPscq7tAXyLii+k2AADA
JicXNDwmdT2cx+ri7kX6b6S/23XqxV38sUroumXvS6za9Wqa90cj0jO0738c
uo+uXcdq/4z4c3vpl4IrbAMAAA0TNAAAAADZNP/UCQAAAKAeggYAAAAgG0ED
AAAAkI2gAQAAAMhG0AAAAABkI2gAAAAAshE0AAAAANkIGgAAAIBsBA0AAABA
NoIGAAAAIBtBAwAAAJCNoAEAAADIRtAAAAAAZCNoAAAAALIRNAAAAADZCBoA
AACAbAQNAAAAQDaCBgAAACAbQQMAAACQjaABAAAAyEbQAAAAAGQjaAAAAACy
ETQAAAAA2QgaAAAAgGwEDQAAAEA2ggYAAAAgG0EDAAAAkI2gAQAAAMhG0AAA
AABkI2gAAAAAshE0AAAAANkIGgAAAIBsBA0AAABANoIGAAAAIBtBAwAAAJCN
oAEAAADIRtAAAAAAZCNoAAAAALIRNAAAAADZCBoAAACAbAQNAAAAQDaCBgAA
ACAbQQMAAACQjaABAAAAyEbQAAAAAGQjaAAAAACyETQAAAAA2QgaAAAAgGwE
DQAAAEA2ggYAAAAgG0EDAAAAkI2gAQAAAMhG0AAAAABkI2gAAAAAshE0AAAA
ANn8f1MBUQvMyGUHAAAAAElFTkSuQmCC
";

const responseJson = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });

function normalize(value: unknown) {
  return String(value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim().toLowerCase();
}
function slug(value: unknown) {
  return normalize(value).replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "evento";
}
function esc(value: unknown) {
  return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function brl(value: unknown) {
  const n = Number(value || 0);
  return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" })
    .format(Number.isFinite(n) ? n : 0);
}
function dateBr(value: unknown) {
  const m = String(value || "").slice(0, 10).match(/^(\d{4})-(\d{2})-(\d{2})$/);
  return m ? m[3] + "/" + m[2] + "/" + m[1] : "";
}
function dueDate(value: unknown) {
  const m = String(value || "").slice(0, 10).match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!m) return "";
  const d = new Date(Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]), 12));
  d.setUTCDate(d.getUTCDate() - 7);
  return new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(d);
}
function endTime(start: string, duration: number | null) {
  if (!start || duration == null || !Number.isFinite(duration)) return "";
  const parts = start.split(":");
  const h = Number(parts[0]), m = Number(parts[1] || 0);
  if (!Number.isFinite(h) || !Number.isFinite(m)) return "";
  const total = h * 60 + m + Math.round(duration * 60);
  return String(Math.floor(total / 60) % 24).padStart(2, "0") + ":" + String(total % 60).padStart(2, "0");
}
function formatDoc(value: unknown) {
  const d = String(value ?? "").replace(/\D/g, "");
  if (d.length === 11) return d.replace(/^(\d{3})(\d{3})(\d{3})(\d{2})$/, "$1.$2.$3-$4");
  if (d.length === 14) return d.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/, "$1.$2.$3/$4-$5");
  return d;
}
function moneyWords(amount: number): string {
  if (!Number.isFinite(amount)) return "Zero reais";
  const units = ["", "um", "dois", "três", "quatro", "cinco", "seis", "sete", "oito", "nove"];
  const teens = ["dez", "onze", "doze", "treze", "quatorze", "quinze", "dezesseis", "dezessete", "dezoito", "dezenove"];
  const tens = ["", "dez", "vinte", "trinta", "quarenta", "cinquenta", "sessenta", "setenta", "oitenta", "noventa"];
  const hundreds = ["", "cento", "duzentos", "trezentos", "quatrocentos", "quinhentos", "seiscentos", "setecentos", "oitocentos", "novecentos"];
  const group = (n: number) => {
    if (!n) return "";
    if (n === 100) return "cem";
    const c = Math.floor(n / 100), d = Math.floor((n % 100) / 10), u = n % 10;
    const p: string[] = [];
    if (c) p.push(hundreds[c]);
    if (d === 1) p.push(teens[u]); else { if (d > 1) p.push(tens[d]); if (u) p.push(units[u]); }
    return p.join(" e ");
  };
  const integer = (n: number) => {
    if (!n) return "zero";
    const millions = Math.floor(n / 1000000);
    const thousands = Math.floor((n % 1000000) / 1000);
    const rest = n % 1000;
    const p: string[] = [];
    if (millions) p.push(millions === 1 ? "um milhão" : group(millions) + " milhões");
    if (thousands) p.push(thousands === 1 ? "mil" : group(thousands) + " mil");
    if (rest) p.push(group(rest));
    return p.join(rest < 100 && (millions || thousands) ? " e " : " ");
  };
  const rounded = Math.round(Math.abs(amount) * 100) / 100;
  const whole = Math.floor(rounded), cents = Math.round((rounded - whole) * 100);
  let out = whole ? integer(whole) + (whole === 1 ? " real" : " reais") : "";
  if (cents) out += (out ? " e " : "") + group(cents) + (cents === 1 ? " centavo" : " centavos");
  if (!out) out = "zero reais";
  return out.charAt(0).toUpperCase() + out.slice(1);
}
function parseNotes(raw: unknown): Record<string, any> {
  if (!raw) return {};
  if (typeof raw === "object" && !Array.isArray(raw)) return raw as Record<string, any>;
  if (typeof raw !== "string") return {};
  try {
    const p = JSON.parse(raw);
    return p && typeof p === "object" && !Array.isArray(p) ? p : {};
  } catch {
    const time = raw.match(/^Horário\s*:\s*(.+?)\s*$/imu)?.[1]?.trim();
    return time ? { event_time: time } : {};
  }
}
function selectedEntries(selected: any): Array<{ id?: string; name?: string }> {
  if (!selected) return [];
  if (Array.isArray(selected)) return selected.flatMap((v: any) => {
    if (typeof v === "string") return [{ id: v, name: v }];
    if (v && typeof v === "object") {
      const id = v.id || v.drink_id, name = v.name || v.nome;
      return id || name ? [{ id, name }] : [];
    }
    return [];
  });
  if (Array.isArray(selected.items)) return selected.items.map((v: any) => ({ id: v.drink_id || v.id, name: v.name || v.nome }));
  if (Array.isArray(selected.ids)) return selected.ids.map((id: string) => ({ id }));
  return [];
}
function resolveDrinks(selected: any, catalog: any[]) {
  const seen = new Set<string>();
  return selectedEntries(selected).flatMap((entry) => {
    const found = (entry.id ? catalog.find((d) => String(d.id) === String(entry.id)) : undefined) ||
      (entry.name ? catalog.find((d) => normalize(d.nome) === normalize(entry.name)) : undefined);
    const name = String(found?.nome || entry.name || entry.id || "").trim();
    if (!name) return [];
    const key = String(found?.id || normalize(name));
    if (seen.has(key)) return [];
    seen.add(key);
    return [{ id: key, name, description: String(found?.descricao || "").trim(), category: found?.categoria || undefined }];
  });
}
function weight(d: any) {
  const nl = Math.max(1, Math.ceil(String(d.name || "").length / 30));
  const desc = String(d.description || "");
  const dl = desc ? Math.max(1, Math.ceil(desc.length / 58)) : 0;
  return 1.15 + (nl - 1) * 0.35 + dl * 0.72;
}
function paginate(drinks: any[], max = 18.5) {
  if (!drinks.length) return [[]];
  const pages: any[][] = []; let current: any[] = []; let total = 0;
  for (const d of drinks) {
    const w = weight(d);
    if (current.length && total + w > max) { pages.push(current); current = []; total = 0; }
    current.push(d); total += w;
  }
  if (current.length) pages.push(current);
  return pages;
}
function personalization(event: any, custom?: string | null) {
  const type = normalize(event.event_type);
  const eventName = String(custom || event.event_name || event.client_name || "").trim();
  if (type.includes("casamento")) {
    const names = [event.groom_name, event.bride_name].filter(Boolean);
    const fallback = eventName.split(/\s*(?:&| e )\s*/i).filter(Boolean);
    const r = names.length ? names : fallback;
    return {
      kind: "wedding",
      initials: r.slice(0, 2).map((n: string) => String(n).trim().charAt(0).toUpperCase()).join(""),
      label: r.length >= 2 ? r.slice(0, 2).join(" & ") : eventName,
      date: event.date ? dateBr(event.date).replace(/\//g, ".") : undefined,
    };
  }
  if (type.includes("anivers")) return { kind: "birthday", label: custom || "Happy Birthday" };
  if (type.includes("corporat") || type.includes("confratern")) return { kind: "corporate", label: eventName || "Cheers!" };
  if (type.includes("despedida") || type.includes("solteir")) return { kind: "bachelor", label: custom || "Game Over" };
  return { kind: "generic", label: eventName };
}
async function callJson(url: string, key: string, fn: string, body: any, requestId: string) {
  const r = await fetch(url + "/functions/v1/" + fn, {
    method: "POST",
    headers: { Authorization: "Bearer " + key, apikey: key, "Content-Type": "application/json", "x-request-id": requestId },
    body: JSON.stringify(body),
  });
  const raw = await r.text();
  let p: any = {};
  try { p = raw ? JSON.parse(raw) : {}; } catch { p = { error: raw.slice(0, 500) }; }
  if (!r.ok || p?.success === false || p?.ok === false) {
    const e: any = new Error(p?.error || p?.message || ("Falha em " + fn + " (HTTP " + r.status + ")."));
    e.status = r.status; e.payload = p; throw e;
  }
  return p;
}
async function callPdf(url: string, key: string, fn: string, body: any, requestId: string) {
  const r = await fetch(url + "/functions/v1/" + fn, {
    method: "POST",
    headers: { Authorization: "Bearer " + key, apikey: key, "Content-Type": "application/json", "x-request-id": requestId },
    body: JSON.stringify(body),
  });
  if (!r.ok) {
    const raw = await r.text(); let message = raw.slice(0, 500);
    try { const p = JSON.parse(raw); message = p.error || p.message || message; } catch {}
    const e: any = new Error(message || ("Falha em " + fn)); e.status = r.status; throw e;
  }
  const bytes = new Uint8Array(await r.arrayBuffer());
  if (bytes.length < 5 || new TextDecoder().decode(bytes.slice(0, 5)) !== "%PDF-") throw new Error("O gerador não retornou um PDF válido.");
  return bytes;
}
async function digest(bytes: Uint8Array) {
  const d = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(d)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
function b64(bytes: Uint8Array) {
  let s = ""; const size = 0x8000;
  for (let i = 0; i < bytes.length; i += size) s += String.fromCharCode(...bytes.subarray(i, Math.min(i + size, bytes.length)));
  return btoa(s);
}
function renderContract(template: any, vars: Record<string, string>) {
  const schema = template?.variables_schema;
  let body = schema && typeof schema === "object" && !Array.isArray(schema) && typeof schema.content === "string"
    ? schema.content : String(template?.description || "");
  body = body.replace(/(\{\{\s*[\w.]+\s*\}\})(?:x{1,4})/gi, "$1").replace(/(\[\s*[\w._]+\s*\])(?:x{1,4})/gi, "$1");
  for (const [key, value] of Object.entries(vars)) {
    if (!value) continue;
    const safeKey = key.replace(/\./g, "\\.");
    body = body
      .replace(new RegExp("\\{\\{\\s*" + safeKey + "\\s*\\}\\}(?:xx|x)?", "gi"), esc(value))
      .replace(new RegExp("\\[\\s*" + safeKey.toUpperCase() + "\\s*\\](?:xx|x)?", "gi"), esc(value));
  }
  const unresolved = Array.from(new Set(Array.from(body.matchAll(/\{\{\s*([a-zA-Z0-9._]+)\s*\}\}|\[([A-Z0-9_]+)\]/g)).map((m) => m[1] || m[2])));
  return { html: body, unresolved };
}
async function signedUrl(admin: any, bucket: string, path: string) {
  const { data, error } = await admin.storage.from(bucket).createSignedUrl(path, 60 * 60 * 24 * 7);
  if (error || !data?.signedUrl) throw error || new Error("Falha ao criar link assinado.");
  return data.signedUrl;
}
async function proposal(admin: any, url: string, key: string, userId: string, eventId: string, requestId: string) {
  const { data: budget, error } = await admin.from("event_budget_versions").select("id").eq("event_id", eventId).eq("is_current", true).maybeSingle();
  if (error) throw error;
  if (!budget?.id) { const e: any = new Error("O evento ainda não possui orçamento atual para gerar a proposta."); e.status = 422; throw e; }
  const p = await callJson(url, key, "canva-generate-proposal", {
    event_id: eventId, budget_version_id: budget.id, requested_by_user_id: userId, internal_source: "gia",
  }, requestId);
  return { success: true, action: "generate_proposal", pdf_url: p.pdf_url, filename: p.filename, proposal_id: p.proposal?.id || null,
    message: "Proposta comercial gerada com sucesso.\n\nPDF: " + p.pdf_url };
}
async function menu(admin: any, url: string, key: string, event: any, requestId: string) {
  const results = await Promise.all([
    admin.from("event_budget_versions").select("selected_drinks").eq("event_id", event.id).eq("is_current", true).maybeSingle(),
    admin.from("drinks").select("id,nome,descricao,categoria"),
    admin.from("event_menu_settings").select("*").eq("event_id", event.id).maybeSingle(),
  ]);
  if (results[0].error) throw results[0].error;
  if (results[1].error) throw results[1].error;
  const drinks = resolveDrinks(results[0].data?.selected_drinks || event.drinks || [], results[1].data || []);
  if (!drinks.length) { const e: any = new Error("O orçamento atual não possui drinks válidos para gerar o cardápio."); e.status = 422; throw e; }
  const pages = paginate(drinks); const tw = drinks.reduce((s, d) => s + weight(d), 0);
  const layout = drinks.length <= 5 && tw <= 10 ? "expanded" : (drinks.length <= 8 && pages.length === 1 && tw <= 15 ? "standard" : "compact");
  const settings = results[2].data;
  const model = { title: "Menu", subtitle: event.event_name || undefined, drinks, layout, columns: 1, pages,
    personalization: personalization(event, settings?.custom_label), artworkMode: settings?.artwork_mode || "automatic",
    artworkUrl: settings?.artwork_url || null, warnings: [] };
  const pdf = await callPdf(url, key, "event-menu-render-pdf", { menu: model, logoDataUrl: MENU_LOGO_DATA_URL, internal_source: "gia" }, requestId);
  const filename = "cardapio-" + slug(event.event_name || event.client_name) + ".pdf";
  const path = "events/" + event.id + "/menus/" + Date.now() + "-" + filename;
  const up = await admin.storage.from("generated-event-menus").upload(path, pdf, { contentType: "application/pdf", upsert: false, cacheControl: "3600" });
  if (up.error) throw up.error;
  const link = await signedUrl(admin, "generated-event-menus", path);
  return { success: true, action: "generate_menu", pdf_url: link, filename, storage_path: path, expires_in: "7 dias",
    message: "Cardápio gerado com sucesso.\n\nPDF: " + link };
}
async function contractRecords(admin: any, event: any) {
  const cr = await admin.from("event_contracts").select("*").eq("event_id", event.id).neq("status", "cancelled").order("created_at", { ascending: false });
  if (cr.error) throw cr.error;
  if ((cr.data || []).length > 1) { const e: any = new Error("Há mais de um contrato ativo neste evento. Regularize a duplicidade antes de enviar para assinatura."); e.status = 409; throw e; }
  let contract = cr.data?.[0] || null;
  let template: any = null, signer: any = null;
  if (contract?.template_id) template = (await admin.from("contract_templates").select("*").eq("id", contract.template_id).maybeSingle()).data;
  if (!template) {
    const q = await admin.from("contract_templates").select("*").eq("is_default", true).eq("status", "active").order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (q.error) throw q.error; template = q.data;
  }
  if (!template) { const e: any = new Error("Nenhum template oficial ativo de contrato está configurado."); e.status = 422; throw e; }
  if (contract?.signer_id) signer = (await admin.from("contract_signers").select("*").eq("id", contract.signer_id).eq("is_active", true).maybeSingle()).data;
  if (!signer) {
    const q = await admin.from("contract_signers").select("*").eq("is_active", true).order("name", { ascending: true }).limit(1).maybeSingle();
    if (q.error) throw q.error; signer = q.data;
  }
  if (!signer) { const e: any = new Error("Nenhum responsável legal ativo da Goat Bar está configurado."); e.status = 422; throw e; }
  const bq = await admin.from("event_budget_versions").select("*").eq("event_id", event.id).eq("is_current", true).maybeSingle();
  if (bq.error) throw bq.error;
  if (!bq.data) { const e: any = new Error("O evento não possui orçamento atual para compilar o contrato."); e.status = 422; throw e; }
  if (!contract) {
    const ins = await admin.from("event_contracts").insert({ event_id: event.id, template_id: template.id, signer_id: signer.id,
      budget_version_id: bq.data.id, status: "draft", version: 1, generated_at: new Date().toISOString() }).select().single();
    if (ins.error || !ins.data) throw ins.error || new Error("Falha ao criar registro do contrato."); contract = ins.data;
  } else if (!contract.template_id || !contract.signer_id || !contract.budget_version_id) {
    const upd = await admin.from("event_contracts").update({ template_id: contract.template_id || template.id, signer_id: contract.signer_id || signer.id,
      budget_version_id: contract.budget_version_id || bq.data.id, updated_at: new Date().toISOString() }).eq("id", contract.id).select().single();
    if (upd.error || !upd.data) throw upd.error || new Error("Falha ao completar dados do contrato."); contract = upd.data;
  }
  return { contract, template, signer, budget: bq.data };
}
async function contractVars(admin: any, event: any, budget: any, signer: any) {
  const q = await Promise.all([
    admin.from("event_contract_client_data").select("*").eq("event_id", event.id).maybeSingle(),
    admin.from("drinks").select("id,nome"),
  ]);
  const client = q[0].data, notes = parseNotes(client?.notes);
  const start = String(notes.event_time || notes.horario || notes.eventTime || event.event_time || "").trim();
  const duration = event.duration_hours == null ? null : Number(event.duration_hours);
  const total = Number(budget.final_budget_value ?? event.current_budget_value ?? 0);
  const guests = Number(event.guests || budget.guest_count || 0);
  const perPerson = Number(budget.average_value_per_person || (total > 0 && guests > 0 ? total / guests : 0));
  const names = resolveDrinks(budget.selected_drinks || event.drinks || [], q[1].data || []).map((d) => d.name);
  const vars: Record<string, string> = {
    "cliente.nome": String(client?.client_name || event.client_name || "").trim(),
    "cliente.documento": formatDoc(client?.cpf_cnpj || notes.cpf_cnpj || ""),
    "cliente.email": String(client?.email || event.email || "").trim(),
    "evento.data": dateBr(event.date),
    "evento.hora_inicio": start,
    "evento.hora_fim": endTime(start, duration),
    "evento.endereco_local": String(notes.venue_address || client?.address || event.event_location || "").trim(),
    "evento.convidados": guests > 0 ? String(guests) : "",
    "evento.valor_por_pessoa": perPerson > 0 ? brl(perPerson) : "",
    "evento.valor_por_pessoa_extenso": perPerson > 0 ? moneyWords(perPerson) : "",
    "financeiro.valor_total": total > 0 ? brl(total) : "",
    "financeiro.valor_total_extenso": total > 0 ? moneyWords(total) : "",
    "financeiro.data_pagamento_final": dueDate(event.date),
    "empresa.responsavel": String(signer.name || "").trim(),
    "empresa.cpf_responsavel": formatDoc(signer.cpf),
    "empresa.endereco_responsavel": String(signer.address || "").trim(),
    "cardapio.drinks": names.join(", "),
    "geral.data_emissao": new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Sao_Paulo" }).format(new Date()),
  };
  const required = ["cliente.nome","cliente.documento","evento.data","evento.hora_inicio","evento.hora_fim","evento.endereco_local",
    "evento.convidados","evento.valor_por_pessoa","evento.valor_por_pessoa_extenso","financeiro.valor_total","financeiro.valor_total_extenso",
    "financeiro.data_pagamento_final","empresa.responsavel","empresa.cpf_responsavel","empresa.endereco_responsavel","cardapio.drinks"];
  const missing = required.filter((k) => !vars[k]);
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(vars["cliente.email"])) missing.push("cliente.email");
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(signer.email || ""))) missing.push("empresa.email_responsavel");
  return { vars, missing };
}
async function contractAndSend(admin: any, url: string, key: string, userId: string, event: any, requestId: string) {
  const r = await contractRecords(admin, event), contract = r.contract;
  const active = await admin.from("contract_signature_requests").select("id,dispatch_status").eq("contract_id", contract.id)
    .eq("signature_provider", "assinafy").eq("document_kind", "contract").neq("dispatch_status", "obsolete")
    .order("created_at", { ascending: false }).limit(1).maybeSingle();
  if (active.data && ["pending_signature","signed","completed"].includes(active.data.dispatch_status)) {
    let link = contract.signed_file_url || contract.generated_file_url || null;
    if (!link && contract.generated_file_path) { try { link = await signedUrl(admin, "contract-documents", contract.generated_file_path); } catch {} }
    return { success: true, action: "generate_contract_and_send", reused: true, contract_id: contract.id,
      signature_request_id: active.data.id, signature_status: active.data.dispatch_status, pdf_url: link,
      message: "O contrato já havia sido enviado para assinatura; o envio existente foi reutilizado." + (link ? "\n\nPDF: " + link : "") };
  }
  const cv = await contractVars(admin, event, r.budget, r.signer);
  if (cv.missing.length) { const e: any = new Error("Não foi possível gerar o contrato. Campos obrigatórios pendentes: " + cv.missing.join(", ") + "."); e.status = 422; e.missing_fields = cv.missing; throw e; }
  const rendered = renderContract(r.template, cv.vars);
  if (rendered.unresolved.length) { const e: any = new Error("O template ainda possui campos não resolvidos: " + rendered.unresolved.join(", ") + "."); e.status = 422; e.missing_fields = rendered.unresolved; throw e; }
  const title = "Contrato Goat Bar - " + String(event.event_name || event.client_name || "Evento").trim();
  const pdf = await callPdf(url, key, "contract-render-pdf", { html: rendered.html, title, contractId: contract.id,
    requested_by_user_id: userId, internal_source: "gia" }, requestId);
  const hash = await digest(pdf), filename = "contrato-" + slug(event.event_name || event.client_name) + ".pdf";
  const path = "events/" + event.id + "/contracts/" + contract.id + "/" + hash.slice(0, 16) + "-" + filename;
  const up = await admin.storage.from("contract-documents").upload(path, pdf, { contentType: "application/pdf", upsert: true, cacheControl: "3600" });
  if (up.error) throw up.error;
  const link = await signedUrl(admin, "contract-documents", path);
  const snapshot = contract.legal_snapshot || {
    captured_at: new Date().toISOString(),
    cliente: { nome: cv.vars["cliente.nome"], documento: cv.vars["cliente.documento"], email: cv.vars["cliente.email"] },
    empresa: { responsavel: cv.vars["empresa.responsavel"], cpf_responsavel: cv.vars["empresa.cpf_responsavel"], endereco_responsavel: cv.vars["empresa.endereco_responsavel"] },
    evento: { data: cv.vars["evento.data"], convidados: cv.vars["evento.convidados"], valor_por_pessoa: cv.vars["evento.valor_por_pessoa"], valor_por_pessoa_extenso: cv.vars["evento.valor_por_pessoa_extenso"] },
    financeiro: { valor_total: cv.vars["financeiro.valor_total"], data_vencimento: cv.vars["financeiro.data_pagamento_final"] },
    cardapio: { drinks: cv.vars["cardapio.drinks"] },
  };
  const save = await admin.from("event_contracts").update({ legal_snapshot: snapshot, generated_file_path: path, generated_file_url: link,
    generated_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", contract.id);
  if (save.error) throw save.error;
  const dispatch = await callJson(url, key, "assinafy-create-doc", { contractId: contract.id, documentKind: "contract", pdfBase64: b64(pdf),
    pdfHash: hash, documentTitle: title, requested_by_user_id: userId, internal_source: "gia" }, requestId);
  return { success: true, action: "generate_contract_and_send", contract_id: contract.id, pdf_url: link, filename,
    signature_request_id: dispatch.signatureRequestId || null, signature_status: dispatch.status || "pending_signature",
    dispatch_outcome: dispatch.dispatchOutcome || null, external_document_id: dispatch.externalDocumentId || null,
    message: (dispatch.message || "Contrato enviado para assinatura com sucesso.") + "\n\nPDF: " + link };
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return responseJson({ success: false, error: "Método não permitido." }, 405);
  const requestId = req.headers.get("x-request-id") || crypto.randomUUID();
  try {
    const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
    const url = (Deno.env.get("SUPABASE_URL") || "").replace(/\/$/, "");
    if (!key || req.headers.get("Authorization") !== "Bearer " + key) return responseJson({ success: false, error: "Acesso interno não autorizado." }, 401);
    const body = await req.json(), action = String(body?.action || ""), eventId = String(body?.event_id || "").trim();
    const userId = String(body?.requested_by_user_id || "").trim();
    if (!eventId || !userId) return responseJson({ success: false, error: "event_id e requested_by_user_id são obrigatórios." }, 422);
    const admin = createClient(url, key, { auth: { persistSession: false } });
    const user = await admin.auth.admin.getUserById(userId);
    if (user.error || !user.data?.user) return responseJson({ success: false, error: "Usuário solicitante não encontrado." }, 403);
    const ev = await admin.from("events").select("*").eq("id", eventId).single();
    if (ev.error || !ev.data) return responseJson({ success: false, error: "Evento não encontrado." }, 404);
    console.info("[goat-ai-document-actions]", { requestId, action, eventId, userId, channel: body?.channel || null });
    if (action === "generate_proposal") return responseJson(await proposal(admin, url, key, userId, eventId, requestId));
    if (action === "generate_menu") return responseJson(await menu(admin, url, key, ev.data, requestId));
    if (action === "generate_contract_and_send") return responseJson(await contractAndSend(admin, url, key, userId, ev.data, requestId));
    return responseJson({ success: false, error: "Ação de documento desconhecida." }, 400);
  } catch (error: any) {
    console.error("[goat-ai-document-actions][error]", { requestId, message: error?.message || String(error), status: error?.status || 500 });
    return responseJson({ success: false, error: error?.message || "Falha interna no processamento do documento.",
      missing_fields: error?.missing_fields || undefined }, Number(error?.status) || 500);
  }
});
