/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DrinksRouteImport } from './routes/drinks'
import { Route as ControladoriaRouteImport } from './routes/controladoria'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosEventoEventoIdRouteImport } from './routes/pos-evento.$eventoId'
import { Route as EventosEventoIdRouteImport } from './routes/eventos.$eventoId'
import { Route as ContratoFormEventoIdRouteImport } from './routes/contrato.form.$eventoId'
import { Route as ContratoDadosTokenRouteImport } from './routes/contrato.dados.$token'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksRoute = DrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => rootRouteImport,
} as any)
const ControladoriaRoute = ControladoriaRouteImport.update({
  id: '/controladoria',
  path: '/controladoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosEventoEventoIdRoute = PosEventoEventoIdRouteImport.update({
  id: '/pos-evento/$eventoId',
  path: '/pos-evento/$eventoId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosEventoIdRoute = EventosEventoIdRouteImport.update({
  id: '/$eventoId',
  path: '/$eventoId',
  getParentRoute: () => EventosRoute,
} as any)
const ContratoFormEventoIdRoute = ContratoFormEventoIdRouteImport.update({
  id: '/contrato/form/$eventoId',
  path: '/contrato/form/$eventoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratoDadosTokenRoute = ContratoDadosTokenRouteImport.update({
  id: '/contrato/dados/$token',
  path: '/contrato/dados/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/controladoria': typeof ControladoriaRoute
  '/drinks': typeof DrinksRoute
  '/eventos': typeof EventosRouteWithChildren
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/vendas': typeof VendasRoute
  '/eventos/$eventoId': typeof EventosEventoIdRoute
  '/pos-evento/$eventoId': typeof PosEventoEventoIdRoute
  '/contrato/dados/$token': typeof ContratoDadosTokenRoute
  '/contrato/form/$eventoId': typeof ContratoFormEventoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/controladoria': typeof ControladoriaRoute
  '/drinks': typeof DrinksRoute
  '/eventos': typeof EventosRouteWithChildren
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/vendas': typeof VendasRoute
  '/eventos/$eventoId': typeof EventosEventoIdRoute
  '/pos-evento/$eventoId': typeof PosEventoEventoIdRoute
  '/contrato/dados/$token': typeof ContratoDadosTokenRoute
  '/contrato/form/$eventoId': typeof ContratoFormEventoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/controladoria': typeof ControladoriaRoute
  '/drinks': typeof DrinksRoute
  '/eventos': typeof EventosRouteWithChildren
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/vendas': typeof VendasRoute
  '/eventos/$eventoId': typeof EventosEventoIdRoute
  '/pos-evento/$eventoId': typeof PosEventoEventoIdRoute
  '/contrato/dados/$token': typeof ContratoDadosTokenRoute
  '/contrato/form/$eventoId': typeof ContratoFormEventoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/contratos'
    | '/controladoria'
    | '/drinks'
    | '/eventos'
    | '/inventario'
    | '/login'
    | '/vendas'
    | '/eventos/$eventoId'
    | '/pos-evento/$eventoId'
    | '/contrato/dados/$token'
    | '/contrato/form/$eventoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/contratos'
    | '/controladoria'
    | '/drinks'
    | '/eventos'
    | '/inventario'
    | '/login'
    | '/vendas'
    | '/eventos/$eventoId'
    | '/pos-evento/$eventoId'
    | '/contrato/dados/$token'
    | '/contrato/form/$eventoId'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/contratos'
    | '/controladoria'
    | '/drinks'
    | '/eventos'
    | '/inventario'
    | '/login'
    | '/vendas'
    | '/eventos/$eventoId'
    | '/pos-evento/$eventoId'
    | '/contrato/dados/$token'
    | '/contrato/form/$eventoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContratosRoute: typeof ContratosRoute
  ControladoriaRoute: typeof ControladoriaRoute
  DrinksRoute: typeof DrinksRoute
  EventosRoute: typeof EventosRouteWithChildren
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  VendasRoute: typeof VendasRoute
  PosEventoEventoIdRoute: typeof PosEventoEventoIdRoute
  ContratoDadosTokenRoute: typeof ContratoDadosTokenRoute
  ContratoFormEventoIdRoute: typeof ContratoFormEventoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks': {
      id: '/drinks'
      path: '/drinks'
      fullPath: '/drinks'
      preLoaderRoute: typeof DrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controladoria': {
      id: '/controladoria'
      path: '/controladoria'
      fullPath: '/controladoria'
      preLoaderRoute: typeof ControladoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-evento/$eventoId': {
      id: '/pos-evento/$eventoId'
      path: '/pos-evento/$eventoId'
      fullPath: '/pos-evento/$eventoId'
      preLoaderRoute: typeof PosEventoEventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$eventoId': {
      id: '/eventos/$eventoId'
      path: '/$eventoId'
      fullPath: '/eventos/$eventoId'
      preLoaderRoute: typeof EventosEventoIdRouteImport
      parentRoute: typeof EventosRoute
    }
    '/contrato/form/$eventoId': {
      id: '/contrato/form/$eventoId'
      path: '/contrato/form/$eventoId'
      fullPath: '/contrato/form/$eventoId'
      preLoaderRoute: typeof ContratoFormEventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrato/dados/$token': {
      id: '/contrato/dados/$token'
      path: '/contrato/dados/$token'
      fullPath: '/contrato/dados/$token'
      preLoaderRoute: typeof ContratoDadosTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventosRouteChildren {
  EventosEventoIdRoute: typeof EventosEventoIdRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosEventoIdRoute: EventosEventoIdRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContratosRoute: ContratosRoute,
  ControladoriaRoute: ControladoriaRoute,
  DrinksRoute: DrinksRoute,
  EventosRoute: EventosRouteWithChildren,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  VendasRoute: VendasRoute,
  PosEventoEventoIdRoute: PosEventoEventoIdRoute,
  ContratoDadosTokenRoute: ContratoDadosTokenRoute,
  ContratoFormEventoIdRoute: ContratoFormEventoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
